import type { LearningLessonSection, LearningLessonStatus } from '../../types.ts';
import type { LearningChapterSeed } from '../seed.ts';
import { isApprovedLesson } from './approval.ts';

// Each lessonSeed below is one node in the lesson table of contents.
// Concept panels inside a lesson are slides/steps, not TOC nodes.
export const chapters: LearningChapterSeed[] = [
  {
    id: 'llm-from-scratch-orientation',
    textKey: 'llmFromScratchOrientation',
    lessonIds: [
      lessonSeed(
        'minimal-llm-project-skeleton',
        'Requirements',
        'Yêu cầu chuẩn bị',
        [],
        ['theory'],
        'next',
      ),
      lessonSeed(
        'llm-from-scratch-roadmap',
        'LLM from scratch roadmap',
        'Roadmap LLM from Scratch',
        [],
        ['theory'],
        'available',
      ),
      lessonSeed(
        'llm-component-checkpoint-quiz',
        'Roadmap checkpoint quiz',
        'Quiz',
        [],
        ['theory'],
        'available',
      ),
    ],
  },
  {
    id: 'text-data-and-tokenization',
    textKey: 'textDataAndTokenization',
    lessonIds: [
      lessonSeed(
        'llm-data-pipeline-overview',
        'LLM data pipeline overview',
        'Pipeline dữ liệu của LLM',
        [],
        ['theory'],
      ),
      lessonSeed(
        'llm-data-pipeline-checkpoint-quiz',
        'LLM data pipeline checkpoint quiz',
        'Quiz',
        [],
        ['theory'],
      ),
      lessonSeed(
        'tokenization-why-it-matters',
        'Why tokenization matters',
        'Tokenization để làm gì?',
        [
          'Tokenization là bước đầu tiên và quan trọng nhất trong việc chuẩn bị dữ liệu văn bản để huấn luyện LLM.',
          'LLM không đọc chữ như con người. Model nhận một dãy số nguyên gọi là token ids, rồi dùng các id đó để tra embedding và xử lý bằng tensor.',
          'Khái niệm tokenization: mục tiêu là chuyển raw text thành những đơn vị nhỏ hơn gọi là token. Token có thể là một từ, một ký tự, một mảnh subword, dấu câu, khoảng trắng, hoặc special token. Cách cắt token quyết định model nhìn văn bản bằng đơn vị nào.',
          'Điểm cần nhớ ở page này: trước khi có attention, loss hay generation, text phải được đổi thành một format số ổn định để model học được.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'tokenization-regex-tokenizer',
        'Regex tokenizer',
        'Tokenizer đơn giản bằng regex',
        [
          'Cách làm đơn giản nhất là dùng regular expressions để tách văn bản theo khoảng trắng hoặc dấu câu. Ví dụ `I love tokenization!` có thể được cắt thành `I`, `love`, `tokenization`, `!`. Cách này dễ hiểu và rất hợp để học from scratch vì bạn nhìn được dòng dữ liệu đi qua từng bước.',
          'Hạn chế của tokenizer đơn giản là unknown words. Nếu vocabulary chỉ có những token đã thấy trong tập train, một từ mới hoặc một biến thể lạ có thể không có id tương ứng. Khi đó hệ thống phải dùng token đặc biệt như `<unk>`, hoặc tokenizer sẽ không encode được input một cách ổn định.',
          'Page này chỉ cần hiểu trade-off: regex tokenizer dễ code và dễ debug, nhưng chưa đủ tốt cho dữ liệu thật vì ngôn ngữ luôn có từ mới, ký hiệu mới và cách viết mới.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'tokenization-token-ids-vocabulary',
        'Token IDs and vocabulary',
        'Token IDs và vocabulary',
        [
          'Chuyển token sang token IDs: sau khi có danh sách token, mỗi token cần được đổi thành một số nguyên duy nhất. Bước này cần một vocabulary, tức mapping hai chiều giữa token và id. Trong code tối thiểu, bạn thường thấy `stoi` để map string token sang integer id, và `itos` để map id ngược lại thành string token.',
          'Vocabulary không chỉ là danh sách từ. Nó là contract giữa tokenizer, dataset, embedding table và output head. Nếu token `hello` có id `42`, embedding layer sẽ dùng id `42` để lấy vector của token đó; khi generation sinh ra id `42`, decoder cũng phải đổi lại được thành `hello`.',
          'Xử lý lỗi bằng special token: với tokenizer dựa trên vocabulary đơn giản, token chưa biết thường được map về `<unk>`. Cách này giúp pipeline không vỡ khi gặp từ lạ, nhưng nó cũng làm mất thông tin vì nhiều từ khác nhau có thể bị gom chung thành cùng một id `<unk>`.',
          'Page này cần giữ một invariant: encode và decode phải dùng cùng vocabulary. Nếu mapping lệch, toàn bộ pipeline phía sau vẫn chạy tensor được nhưng ý nghĩa dữ liệu đã sai.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'tokenization-bpe-tiktoken',
        'BPE and tiktoken',
        'BPE và tiktoken',
        [
          'Byte Pair Encoding (BPE): đây là hướng tokenizer nâng cao được dùng trong các model như GPT-2, GPT-3 và GPT-4. Thay vì thay cả từ lạ bằng `<unk>`, BPE có thể bẻ từ thành các mảnh subword hoặc thậm chí ký tự đơn lẻ. Nhờ vậy tokenizer thường vẫn encode được từ mới mà không cần vocabulary chứa nguyên từ đó.',
          'Trực giác của BPE là giữ vocabulary hữu hạn nhưng vẫn linh hoạt. Những mảnh xuất hiện thường xuyên có thể được merge thành token dài hơn, còn từ hiếm hoặc từ mới vẫn có thể phân rã thành các mảnh nhỏ hơn. Đây là lý do cùng một câu có thể cho ra số token khác nhau tùy tokenizer.',
          'Trong thực hành, ta có thể dùng `tiktoken` của OpenAI để làm việc với tokenizer kiểu GPT. Thư viện này được tối ưu hiệu suất cao, phần lõi viết bằng Rust, và cho phép encode text thành token ids hoặc decode token ids ngược lại thành text để kiểm tra.',
          'Page này chưa yêu cầu tự implement BPE. Mục tiêu là hiểu vì sao model hiện đại dùng subword tokenizer thay vì chỉ tách theo từ.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'tokenization-special-tokens',
        'Special tokens',
        'Special tokens',
        [
          'Special tokens vẫn rất quan trọng dù dùng BPE. Token như `<|endoftext|>` có thể đánh dấu kết thúc văn bản hoặc ngăn cách các tài liệu độc lập. `[BOS]`, `[EOS]`, `[PAD]` hoặc `<unk>` tùy tokenizer/model cũng là token thật, có id thật, và có thể ảnh hưởng loss nếu bạn không xử lý mask đúng.',
          'Các token này không phải trang trí. Chúng nói cho model biết biên của sequence, đâu là padding, đâu là văn bản đã kết thúc, hoặc đâu là token thay thế cho phần tokenizer không nhận ra.',
          'Page này cần nhớ một điều thực dụng: nếu padding hoặc special token bị tính loss sai, model có thể học dự đoán những token kỹ thuật thay vì học ngôn ngữ thật.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'tokenization-data-pipeline',
        'Tokenization pipeline',
        'Pipeline sau tokenization',
        [
          'Pipeline chuẩn bị dữ liệu không dừng ở tokenization. Sau khi text thành token ids, ta còn cần data loader để tạo sliding window: input là một đoạn token ids, target là đoạn đó dịch phải một token. Đây là dữ liệu trực tiếp cho next-token prediction.',
          'Sau data loader, token ids được đưa vào token embedding để thành embedding vectors. Token embedding chỉ biết identity của token, còn positional embedding giúp model biết vị trí của token trong context window. Vì vậy tokenization, sliding window và embedding là ba bước nối nhau rất chặt.',
          'Điểm cần hiểu sâu là tokenizer không chỉ là tiện ích I/O. Nó định nghĩa biên giới của bài toán dự đoán: model không dự đoán "từ tiếp theo" theo nghĩa ngôn ngữ tự nhiên, mà dự đoán token tiếp theo theo vocabulary và thuật toán tokenizer cụ thể.',
          'Khi học from scratch, hãy bắt đầu bằng tokenizer đơn giản để thấy toàn bộ dòng dữ liệu. Sau đó mới thay bằng BPE hoặc tokenizer thật. Điều cốt lõi cần giữ là mapping hai chiều: text -> token ids để train, và token ids -> text để generation có thể đọc được.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'token-counting-hand-quiz',
        'Token counting hand quiz',
        'Quiz tính token bằng tay',
        [
          'Bài này buộc bạn tính token bằng tay để thấy context window là tài nguyên hữu hạn. Trước khi có tokenizer thật, hãy dùng một quy ước đơn giản: tách theo khoảng trắng và giữ dấu câu như token riêng.',
          'Với câu `I love tiny LLMs.`, nếu tách thành `I`, `love`, `tiny`, `LLMs`, `.`, ta có 5 token. Nếu thêm special token `<bos>` ở đầu và `<eos>` ở cuối, sequence trở thành 7 token. Hai token đặc biệt này cũng chiếm chỗ trong context window.',
          'Giả sử context window là 6, câu trên sau khi thêm `<bos>/<eos>` không vừa trong một cửa sổ đầy đủ. Bạn cần quyết định cắt ngắn, bỏ special token, hoặc dùng sliding window. Đây là quyết định dữ liệu, không phải lỗi của model.',
          'Bài tập tính tay: với token ids `[10, 23, 44, 7, 8, 9, 2]` và context window 4, hãy tạo các cặp input-target bằng sliding window stride 1. Input đầu là `[10, 23, 44, 7]`, target đầu là `[23, 44, 7, 8]`.',
          'Câu hỏi kiểm tra: nếu batch gồm 3 cửa sổ, mỗi cửa sổ dài 4, input tensor có shape nào? Nếu vocab size là 50, logits sau model có shape nào? Câu trả lời cần nối token counting với downstream shape, không chỉ đếm số phần tử.',
        ],
        ['theory', 'calculation'],
      ),
      lessonSeed(
        'tokenizer-and-dataloader-code',
        'Tokenizer and dataloader code',
        'Code tokenizer và dataloader',
        [
          'Code step này hiện thực hóa đường đi tối thiểu từ text sang batch, không cố xây tokenizer production. Input là một đoạn text nhỏ và một vocabulary được tạo từ corpus mẫu; output là token ids, các cửa sổ input-target, và batch tensor.',
          'Tokenizer tối thiểu cần hai cấu trúc: `stoi` để map string token sang id, và `itos` để map id về string token. Khi encode, text được cắt theo quy ước đơn giản rồi đổi thành id. Khi decode, id được ghép lại để kiểm tra dòng dữ liệu có mất thông tin nghiêm trọng không.',
          'Theo reference gist, tokenizer thực tế cần xử lý boundary và padding. Trong lab tối thiểu, hãy để sẵn slot cấu hình cho `<|endoftext|>` và `[PAD]`, nhưng chưa cần implement BPE thật. Nếu sequence trong cùng batch dài ngắn khác nhau, padding chỉ là kỹ thuật batching; target padding phải được mask khỏi loss ở bài fine-tuning.',
          'Dataloader nhận dãy token ids dài và tạo sliding windows. Với mỗi vị trí bắt đầu, input lấy `context_window` token, target lấy cùng độ dài nhưng dịch phải một bước. Đây chính là dữ liệu cho next-token prediction.',
          'Batching chỉ gom nhiều cặp input-target lại với nhau. Điều cần quan sát là batch không thay đổi nghĩa của dữ liệu; nó chỉ thêm chiều batch ở đầu. Nếu một sample có shape `(T)`, batch sẽ có shape `(B, T)`.',
          'Khi code chạy đúng, bạn nên in ra một vài sample decode được: input text fragment và target text fragment lệch một token. Nếu mắt bạn thấy target thật sự là "token kế tiếp" của input ở từng vị trí, phần dữ liệu đã sẵn sàng cho model.',
        ],
        ['theory', 'code'],
      ),
    ],
  },
  {
    id: 'attention-and-transformers-from-scratch',
    textKey: 'attentionAndTransformersFromScratch',
    lessonIds: [
      lessonSeed(
        'causal-self-attention-theory',
        'Causal self-attention theory',
        'Lý thuyết causal self-attention',
        [
          'Self-attention cho mỗi token tạo representation mới bằng cách nhìn các token khác trong cùng sequence. Trong LLM decoder-only, attention phải có tính causal: token ở vị trí hiện tại chỉ được đọc chính nó và các token trước đó, không được đọc tương lai.',
          'Ba tensor Q, K, V là ba cách chiếu cùng embedding đầu vào. Query hỏi "vị trí này đang tìm thông tin gì", Key mô tả "mỗi vị trí đang có đặc điểm gì để được chú ý", và Value chứa nội dung sẽ được trộn lại sau khi có trọng số attention.',
          'Attention score được tính bằng Q nhân K chuyển vị, thường chia cho căn bậc hai của head dimension để giữ scale ổn định. Sau đó causal mask đặt các vị trí tương lai thành giá trị rất âm trước softmax, làm xác suất chú ý vào tương lai gần như bằng 0.',
          'Gist nhấn mạnh hai cách nghĩ về mask. Cách dễ hiểu là đặt trọng số tương lai về 0 rồi chuẩn hóa lại từng hàng. Cách hiệu quả hơn trong code là đặt score tương lai thành `-inf` trước softmax, vì `exp(-inf)` gần như bằng 0.',
          'Dropout trong attention chỉ dùng khi training. Nó có thể được áp trên attention weights sau softmax để model không quá phụ thuộc vào một vài liên kết chú ý cụ thể. Khi `model.eval()`, dropout tắt để generation ổn định.',
          'Trong pipeline LLM, causal attention là nơi model xây ngữ cảnh. Token embedding ban đầu chỉ biết identity và vị trí; sau attention, representation của một token đã chứa thông tin từ prefix trước nó trong context window.',
          'Điều cần nhớ là causal mask không làm model "thông minh" hơn, mà làm bài toán training khớp với generation. Khi generate từng token từ trái sang phải, tương lai chưa tồn tại; training cũng phải tôn trọng ràng buộc đó.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'attention-score-shape-calculation',
        'Attention score and shape calculation',
        'Tính score và shape attention',
        [
          'Bài tính tay này giúp bạn kiểm tra attention bằng shape trước khi nhìn code. Giả sử batch size `B = 2`, sequence length `T = 4`, model dimension `C = 8`, số head `H = 2`, vậy mỗi head có dimension `D = 4`.',
          'Sau projection, Q, K, V ban đầu có thể có shape `(B, T, C)`. Khi tách head, shape trở thành `(B, H, T, D)`. Nếu bạn không tách đúng, phép nhân attention sẽ trộn nhầm chiều head với chiều sequence.',
          'Score của từng head là `Q @ K^T` trên chiều `D`, nên shape là `(B, H, T, T)`. Hai chiều `T` có ý nghĩa khác nhau: hàng là vị trí đang hỏi, cột là vị trí được đọc.',
          'Causal mask cho `T = 4` là ma trận tam giác dưới. Hàng 0 chỉ đọc cột 0; hàng 1 đọc cột 0 và 1; hàng 2 đọc cột 0, 1, 2; hàng 3 đọc cả 0..3. Hãy tự đánh dấu những ô bị cấm trước khi softmax.',
          'Sau softmax, trọng số attention nhân với V để tạo context per head có shape `(B, H, T, D)`. Khi ghép head lại, output trở về `(B, T, C)`. Nếu shape cuối không quay về model dimension, GPT block phía sau sẽ không nối residual được.',
        ],
        ['theory', 'calculation'],
      ),
      lessonSeed(
        'multi-head-attention-code',
        'Multi-head attention code',
        'Code multi-head attention',
        [
          'Code step này xây multi-head attention ở mức tối thiểu. Input là tensor embedding có shape `(batch, sequence, model_dim)`; output phải giữ cùng shape để có thể cộng residual trong GPT block.',
          'Bước đầu là tạo linear projection cho Q, K, V. Một implementation gọn có thể dùng ba layer riêng hoặc một layer lớn sinh ra `3 * model_dim` rồi tách. Cách nào cũng phải kiểm tra được shape trước và sau projection.',
          'Tiếp theo, code reshape tensor thành nhiều head: từ `(B, T, C)` sang `(B, H, T, D)`. Đây là điểm dễ sai nhất vì `view`, `transpose`, hoặc `contiguous` có thể làm bạn tưởng shape đúng nhưng thứ tự chiều sai.',
          'Causal mask được tạo theo sequence length hiện tại, áp vào score trước softmax. Trong implementation tối thiểu, mask có thể là một buffer tam giác dưới hoặc một tensor tạo động theo `T`.',
          'Sau softmax, attention dropout có thể zero thêm một số liên kết trong lúc training. Đây là regularization, không phải một phần bắt buộc của phép tính inference. Vì vậy test nên kiểm tra cả mode training và eval nếu sau này lab có code chạy thật.',
          'Output của từng head được ghép lại thành `(B, T, C)` rồi đi qua output projection. Điều cần quan sát khi test là: không token nào nhìn tương lai, attention weights trên mỗi hàng cộng xấp xỉ 1, và output shape không đổi so với input.',
        ],
        ['theory', 'code'],
      ),
    ],
  },
  {
    id: 'gpt-model-from-scratch',
    textKey: 'gptModelFromScratch',
    lessonIds: [
      lessonSeed(
        'gpt-block-theory',
        'GPT block theory',
        'Lý thuyết GPT block',
        [
          'Một GPT block là đơn vị lặp chính của decoder-only Transformer. Nó thường gồm normalization, causal self-attention, residual connection, normalization thứ hai, feed-forward network, và residual connection thứ hai.',
          'Attention trộn thông tin theo chiều sequence: token hiện tại đọc prefix trước nó. Feed-forward network xử lý từng vị trí độc lập theo chiều channel: nó mở rộng model dimension, áp activation, rồi nén về model dimension.',
          'Residual connection giúp block học phần bổ sung thay vì phải viết lại toàn bộ representation. Nếu attention hoặc MLP chưa hữu ích ở đầu training, residual vẫn cho tín hiệu đi qua, làm model sâu dễ train hơn.',
          'Layer normalization giữ activation ở mỗi vị trí có mean gần 0 và variance gần 1 trên chiều channel. Điều này làm training sâu ổn định hơn, nhất là khi gradient có thể quá nhỏ hoặc quá lớn.',
          'MLP trong GPT thường dùng GELU thay vì ReLU đơn giản. GELU là activation mượt hơn: nó không chỉ cắt âm/dương cứng, mà cho tín hiệu đi qua theo một đường cong mềm. Trong course này, GELU là một concept cần biết, chưa cần tự chứng minh công thức.',
          'Trong nhiều GPT hiện đại, dạng pre-norm được dùng: normalize trước attention hoặc MLP, rồi cộng residual sau module. Invariant quan trọng là mỗi block nhận và trả `(B, T, C)` để có thể xếp chồng nhiều lần.',
          'Trong pipeline LLM, nhiều GPT block xếp chồng biến token embedding ban đầu thành representation giàu ngữ cảnh. Block đầu học quan hệ gần và đơn giản; các block sau có thể tổng hợp mẫu dài hơn, dù trong model nhỏ điều này chỉ là trực giác học tập.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'gpt-parameter-shape-calculation',
        'GPT parameter and shape calculation',
        'Tính parameter và shape của GPT',
        [
          'Bài tính này giúp bạn nhìn GPT như một hệ thống shape và parameter, không phải một hộp đen. Giả sử vocab size `V = 1000`, context window `T = 16`, model dimension `C = 64`, số layer `L = 2`, số head `H = 4`.',
          'Token embedding có khoảng `V * C` parameter, tức `1000 * 64 = 64,000`. Positional embedding học được có `T * C = 1,024` parameter. Hai phần này cộng lại tạo input representation shape `(B, T, C)`.',
          'Trong một attention block, nếu Q, K, V mỗi projection là `C x C`, tổng ba projection là `3 * C * C`. Output projection thêm `C * C`. Bỏ qua bias, attention có khoảng `4 * C * C` parameter.',
          'MLP thường mở rộng lên `4C`, nên hai linear layer có `C * 4C + 4C * C = 8C^2` parameter. Với `C = 64`, MLP mỗi block lớn hơn attention trong cách đếm đơn giản này.',
          'Output head đưa representation từ `C` về logits trên `V`, nên có `C * V` parameter nếu không tie weight với embedding. Câu hỏi kiểm tra: với batch size `B = 8`, logits cuối có shape `(8, 16, 1000)`; parameter count không phụ thuộc batch size.',
        ],
        ['theory', 'calculation'],
      ),
      lessonSeed(
        'gpt-module-code',
        'GPT module code',
        'Code module GPT',
        [
          'Code step này ghép các module đã học thành một model decoder-only nhỏ. Input là batch token ids có shape `(B, T)`; output là logits có shape `(B, T, vocab_size)`.',
          'Forward path bắt đầu bằng token embedding lookup để biến id thành vector `(B, T, C)`. Positional embedding được cộng vào để model phân biệt token ở vị trí 0 với token ở vị trí 10, dù token id giống nhau.',
          'Sau đó tensor đi qua một danh sách GPT block. Mỗi block phải giữ shape `(B, T, C)` để residual connection và block tiếp theo hoạt động. Đây là invariant quan trọng nhất của model body.',
          'Reference gist dùng GPT-2 124M làm mốc: transformer block được lặp 12 lần, còn bản lớn hơn lặp nhiều hơn. Trong TorchViz lab, con số layer chỉ là config học tập; mục tiêu là thấy shape và dòng dữ liệu không đổi qua stack block.',
          'Final normalization làm representation ổn định trước output head. Output head là linear layer chiếu từ `C` sang `vocab_size`, tạo logits cho từng vị trí trong sequence.',
          'Điều cần quan sát trong code là contract rõ ràng: model không nhận text, không tự tokenize, không tự tính loss nếu chưa truyền target. Nó chỉ nhận token ids và trả logits; training loop mới quyết định logits được so với target như thế nào.',
        ],
        ['theory', 'code'],
      ),
    ],
  },
  {
    id: 'pretraining-and-generation',
    textKey: 'pretrainingAndGeneration',
    lessonIds: [
      lessonSeed(
        'next-token-pretraining-theory',
        'Next-token pretraining theory',
        'Lý thuyết pretraining next-token',
        [
          'Next-token pretraining dạy model dự đoán token kế tiếp tại mọi vị trí trong một context window. Với input `[x0, x1, x2]`, target tương ứng là `[x1, x2, x3]`. Model học bằng cách làm logits tại mỗi vị trí gần với target token của vị trí đó.',
          'Điểm mạnh của objective này là dữ liệu text thô tự tạo nhãn. Bạn không cần con người gán label cho từng ví dụ; chỉ cần dịch sequence sang phải một token là có target.',
          'Cross-entropy loss đo model đặt xác suất bao nhiêu cho token đúng. Nếu logits làm token đúng có xác suất cao, loss thấp. Nếu model tự tin vào token sai, loss cao. Đây là tín hiệu gradient cho toàn bộ embedding, attention, MLP, và output head.',
          'Causal mask là điều kiện cần để objective không bị gian lận. Nếu token ở vị trí hiện tại nhìn được target ở tương lai, loss có thể thấp nhưng model không học khả năng generation thật.',
          'Validation loss chạy trên dữ liệu không cập nhật weight. Nếu train loss tiếp tục giảm nhưng validation loss đứng yên hoặc tăng, model có thể đang memorizing dữ liệu nhỏ thay vì học pattern tổng quát.',
          'Trong pipeline, pretraining nối dataloader, GPT model, loss, optimizer như AdamW, validation, và checkpoint. Mỗi phần nhỏ có thể đúng riêng lẻ nhưng training vẫn sai nếu input-target bị lệch, mask sai, hoặc logits/target reshape sai trước loss.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'loss-perplexity-hand-calculation',
        'Loss and perplexity calculation',
        'Tính loss và perplexity',
        [
          'Bài này biến loss từ một con số mơ hồ thành phép tính có thể kiểm tra. Giả sử tại một vị trí, vocabulary có 3 token và model sau softmax cho xác suất `[0.7, 0.2, 0.1]`. Nếu target là token 0, cross-entropy là `-log(0.7)`.',
          'Nếu target là token 2, loss là `-log(0.1)`, lớn hơn nhiều vì model đặt xác suất thấp cho đáp án đúng. Cross-entropy không quan tâm token sai nào đứng thứ hai; nó chỉ nhìn xác suất của target đúng.',
          'Với nhiều vị trí trong batch, loss thường là trung bình của cross-entropy trên tất cả token target hợp lệ. Nếu có padding token, bạn cần mask padding ra khỏi loss; trong dataset tối thiểu không padding thì việc này đơn giản hơn.',
          'Perplexity thường được tính là `exp(loss)`. Nếu loss trung bình là `1.0`, perplexity khoảng `2.718`. Trực giác: model đang bối rối tương đương phải chọn giữa khoảng 2.7 token hiệu quả ở mỗi bước.',
          'Bài tập tính tay: cho ba target có xác suất đúng lần lượt `0.5`, `0.25`, `0.125`, hãy tính loss trung bình bằng log tự nhiên và perplexity. Sau đó giải thích vì sao perplexity tăng nhanh khi xác suất target đúng giảm.',
        ],
        ['theory', 'calculation'],
      ),
      lessonSeed(
        'training-loop-and-generation-code',
        'Training loop and generation code',
        'Code training loop và generation',
        [
          'Code step này mô tả training loop tối thiểu, không triển khai training thật trong Learning Lab hiện tại. Input của loop là batch `(x, y)` từ dataloader; output của model là logits; output của loss là một số scalar để optimizer cập nhật tham số.',
          'Một train step gồm: đưa input vào model, reshape logits và target cho cross-entropy, tính loss, zero gradient, backward, optimizer step. Thứ tự này quan trọng vì gradient cũ không được lẫn vào step mới.',
          'Validation chạy cùng forward và loss nhưng không cập nhật tham số. Nó giúp bạn phân biệt model thật sự học pattern tổng quát hay chỉ giảm loss trên batch training vừa thấy.',
          'Checkpoint lưu config, model state, optimizer state nếu cần, và thông tin step. Với project học tập, checkpoint còn là cách kiểm tra reproducibility: cùng config và seed nên cho hành vi gần giống nhau.',
          'Generation là vòng autoregressive: bắt đầu từ prompt token ids, cắt về context window nếu quá dài, lấy logits ở vị trí cuối, chọn token tiếp theo bằng greedy hoặc sampling, nối token mới vào sequence, rồi lặp lại. Điều cần quan sát là generation dùng cùng model nhưng không dùng target hay loss.',
          'Gist có thêm temperature scaling và top-k sampling để tránh output quá đơn điệu của greedy decoding. Temperature thấp làm phân phối sắc hơn; temperature cao làm phân phối đều hơn. Top-k chỉ cho sampling trong nhóm k token có logit cao nhất.',
          'Các kỹ thuật như learning-rate warmup, cosine decay, gradient clipping, và LoRA đã có giải thích trong reference, nhưng cần lab riêng để dạy đúng. Trong course hiện tại, chúng được đánh dấu là placeholder bổ sung, không đưa vào code contract chính.',
        ],
        ['theory', 'code'],
      ),
    ],
  },
  {
    id: 'finetuning-and-alignment',
    textKey: 'finetuningAndAlignment',
    lessonIds: [
      lessonSeed(
        'finetuning-objectives-theory',
        'Fine-tuning objectives theory',
        'Lý thuyết objective fine-tuning',
        [
          'Fine-tuning bắt đầu từ một base model đã học phân phối ngôn ngữ, rồi điều chỉnh nó cho hành vi mục tiêu. Mục tiêu có thể là classification, instruction following, domain adaptation, hoặc preference alignment.',
          'Điểm khác giữa pretraining và fine-tuning nằm chủ yếu ở dữ liệu và objective. Pretraining dùng text liên tục với next-token loss rộng. Fine-tuning dùng ví dụ có cấu trúc hơn: input-label, prompt-response, hoặc cặp response được ưu tiên.',
          'Classification fine-tuning có thể thay hoặc thêm head để dự đoán nhãn. Instruction fine-tuning thường vẫn dùng next-token loss, nhưng chỉ trên phần response hoặc trên format prompt-response được thiết kế rõ.',
          'Classification fine-tuning là bài toán chuyên biệt: model chỉ cần chọn trong tập nhãn đã biết, ví dụ spam/not spam. Instruction fine-tuning linh hoạt hơn vì model học prompt-response cho nhiều task, nhưng thường cần dữ liệu tốt hơn và compute lớn hơn.',
          'Fine-tuning không tự động làm model an toàn hay đúng hơn. Nếu data có lỗi, thiếu refusal phù hợp, hoặc format không nhất quán, model sẽ học cả thói quen xấu đó. Data quality vì vậy là một phần của objective, không chỉ là tiền xử lý.',
          'Trong pipeline, fine-tuning đứng sau pretraining và trước evaluation/deployment. Nó sử dụng lại tokenizer, model architecture, logits, loss, và optimizer, nhưng thay đổi cách tạo example và cách đo hành vi mong muốn.',
        ],
        ['theory'],
      ),
      lessonSeed(
        'instruction-data-quality-quiz',
        'Instruction data quality quiz',
        'Quiz chất lượng instruction data',
        [
          'Bài quiz này kiểm tra xem bạn có nhìn dữ liệu instruction như một objective học được hay không. Một cặp prompt-response tốt phải cho model thấy rõ yêu cầu, ngữ cảnh, giới hạn, và kiểu câu trả lời mong muốn.',
          'Câu hỏi đầu tiên: nếu prompt yêu cầu "giải thích ngắn gọn" nhưng response dài nhiều đoạn và lan man, model sẽ học gì? Nó có thể học rằng instruction về độ dài không quan trọng. Đây là lỗi alignment ở mức dữ liệu.',
          'Câu hỏi thứ hai: nếu dataset chỉ có câu trả lời hoàn hảo và không có ví dụ refusal cho yêu cầu không phù hợp, model có học được khi nào nên từ chối không? Thường là không; hành vi refusal cần được biểu diễn nhất quán trong dữ liệu hoặc objective riêng.',
          'Câu hỏi thứ ba: evaluation example có được trộn vào training không? Nếu có, điểm evaluation sẽ mất ý nghĩa. Bạn cần giữ một tập kiểm tra riêng để đo hành vi sau fine-tuning.',
          'Bài tập phân loại: lấy 5 prompt-response pairs và gắn nhãn `clear`, `ambiguous`, `format mismatch`, `unsafe`, hoặc `leaky evaluation`. Mục tiêu không phải tranh luận đạo đức rộng, mà là kiểm tra liệu dữ liệu có dạy đúng hành vi mà code fine-tuning sắp tối ưu hay không.',
        ],
        ['theory', 'calculation'],
      ),
      lessonSeed(
        'classification-and-instruction-finetune-code',
        'Classification and instruction fine-tune code',
        'Code fine-tune classification và instruction',
        [
          'Code step này phác thảo hai đường fine-tuning phổ biến: classification và instruction. Cả hai dùng lại backbone Transformer, nhưng khác ở cách chuẩn bị batch, target, và metric đánh giá.',
          'Với classification, input là token ids của văn bản hoặc prompt, output mong muốn là nhãn. Code có thể lấy representation ở vị trí cuối hoặc một pooling đơn giản, rồi đưa qua classification head để tạo logits trên số lớp.',
          'Với classification, loss thường chỉ nhìn logits ở token cuối: `model(input_batch)[:, -1, :]`. Accuracy dùng để đánh giá, còn cross-entropy vẫn là loss để backprop vì accuracy không differentiable.',
          'Với instruction fine-tuning, input là chuỗi đã format gồm instruction, optional context, và response. Target thường là token của response; phần prompt hoặc padding có thể được thay bằng `-100` để `cross_entropy(ignore_index=-100)` bỏ qua khi tính loss.',
          'Training loop vẫn giống về cơ chế: forward, loss, backward, optimizer step. Khác biệt nằm ở collator và loss mask. Nếu mask sai, model có thể học copy prompt thay vì học trả lời.',
          'Evaluation cho classification nhìn accuracy, F1, hoặc confusion matrix. Evaluation cho instruction cần prompt held-out và tiêu chí chất lượng response như đúng yêu cầu, đúng format, không bịa theo ngữ cảnh, và refusal hợp lý. Trong pass này, code lesson chỉ mô tả contract đó, chưa chạy fine-tuning thật.',
        ],
        ['theory', 'code'],
      ),
    ],
  },
  {
    id: 'llm-fundamentals',
    textKey: 'llmFundamentals',
    lessonIds: [
      'transformer-at-scale',
      'context-window-limits',
      'kv-cache-inference',
      'tokenization-at-scale',
      'llm-positional-encodings',
      'flash-attention',
      'grouped-query-attention',
      'sliding-window-attention',
      'llm-pretraining',
      'instruction-tuning',
      'rlhf',
      'constitutional-ai',
      'direct-preference-optimization',
      'scaling-laws',
    ],
  },
  {
    id: 'production-prompt-engineering',
    textKey: 'productionPromptEngineering',
    lessonIds: [
      'system-prompt',
      'user-prompt',
      'assistant-turn-history',
      'few-shot-examples',
      'zero-shot-prompting',
      'one-shot-few-shot-prompting',
      'chain-of-thought',
      'self-consistency',
      'react-prompting',
      'tree-of-thought',
      'structured-output-prompting',
      'role-prompting',
      'prompt-chaining',
      'clear-instruction-format-boundaries',
      'prompt-negative-instructions',
      'examples-output-constraints',
      'prompt-versioning-changelogs',
      'prompt-ab-testing',
      'prompt-compression',
      'prompt-injection-defense',
      'promptlayer-tracking',
      'langsmith-observability',
      'openai-playground',
      'anthropic-console',
    ],
  },
  {
    id: 'working-with-ai-apis',
    textKey: 'workingWithAiApis',
    lessonIds: [
      'chat-completions-api',
      'function-calling-tool-use',
      'json-mode-structured-outputs',
      'streaming-responses-sse',
      'embeddings-api',
      'vision-api-gpt4v',
      'assistants-api-file-search',
      'batch-api',
      'token-counting-tiktoken',
      'rate-limits-quotas',
      'anthropic-messages-api',
      'anthropic-system-prompts',
      'anthropic-long-context',
      'anthropic-vision-support',
      'anthropic-tool-use',
      'anthropic-streaming',
      'gemini-models',
      'gemini-multimodal-inputs',
      'gemini-search-grounding',
      'gemini-context-caching',
      'mistral-models',
      'mistral-function-calling',
      'mistral-json-mode',
      'ollama-open-source-models',
      'llama-3-models-api',
      'ollama-local-llama',
      'peft-finetuning-llama',
      'cohere-provider',
      'nvidia-nim',
      'groq-inference',
      'together-ai-hosting',
      'replicate-hosting',
    ],
  },
  {
    id: 'api-integration-patterns',
    textKey: 'apiIntegrationPatterns',
    lessonIds: [
      'count-tokens-before-sending',
      'truncation-strategies',
      'context-window-management',
      'conversation-summarization',
      'sse-streaming-chunks',
      'partial-response-handling',
      'client-stream-rendering',
      'perceived-latency',
      'exponential-backoff-jitter',
      'provider-quota-management',
      'queue-request-management',
      'circuit-breaker-pattern',
      'token-usage-logging',
      'model-routing-by-complexity',
      'prompt-compression-cost-control',
      'sha256-response-caching',
      'async-pipelines',
      'api-error-fallbacks',
    ],
  },
  {
    id: 'secure-api-integration',
    textKey: 'secureApiIntegration',
    lessonIds: [
      'no-frontend-api-keys',
      'env-files-secret-manager',
      'backend-proxy-pattern',
      'redis-per-user-rate-limits',
      'api-key-rotation',
      'logging-monitoring',
    ],
  },
];

function lessonSeed(
  id: string,
  titleEn: string,
  titleVi: string,
  theoryVi: string[],
  sectionKinds: LearningLessonSection['kind'][],
  status?: LearningLessonStatus,
): LearningChapterSeed['lessonIds'][number] {
  if (!isApprovedLesson(id)) {
    return {
      id,
      title: { en: titleEn, vi: titleVi },
    };
  }

  return {
    id,
    title: { en: titleEn, vi: titleVi },
    theory: theoryVi.map((paragraph) => ({ en: paragraph, vi: paragraph })),
    sections: sectionKinds.map((kind) => ({
      kind,
      refId: kind === 'theory' ? id : `${id}-${kind}`,
    })),
    status,
  };
}
