import type { LearningTableOfContents, LearningTocTrackSeed } from '../../../core/learning/types.ts';

const chapters: LearningTocTrackSeed[] = [
  {
    id: 'linear-algebra',
    text: {
      title: { en: "1.1 Linear Algebra", vi: "1.1 Linear Algebra" },
      description: { en: "Vectors, matrices, ML operations, eigenvectors, PCA, and SVD.", vi: "Vector, ma trận, phép toán ML, eigenvector, PCA và SVD." },
    },
    lessonIds: [
      'vectors-intuition',
      'vector-operations',
      'dot-product',
      'vector-norms',
      'unit-vectors-normalization',
      'cosine-similarity',
      'orthogonality',
      'matrix-operations',
      'elementwise-vs-matrix-product',
      'identity-inverse-matrix',
      'determinant-intuition',
      'matrix-rank',
      'linear-transformations',
      'systems-least-squares',
      'matrix-trace',
      'eigenvalues-eigenvectors',
      'pca-eigenvalues',
      'svd-intuition',
      'svd-dimensionality-reduction',
    ],
  },
  {
    id: 'calculus',
    text: {
      title: { en: "1.2 Calculus", vi: "1.2 Calculus" },
      description: { en: "Derivatives, gradients, chain rule, computational graphs, and ML losses.", vi: "Đạo hàm, gradient, chain rule, computational graph và loss trong ML." },
    },
    lessonIds: [
      'derivative-intuition',
      'derivative-rules',
      'derivatives-log-exp-sigmoid',
      'minima-maxima-saddle',
      'second-derivative-convexity',
      'partial-derivatives',
      'gradient-vector',
      'gradient-descent-direction',
      'jacobian-matrix',
      'hessian-matrix',
      'single-variable-chain-rule',
      'multivariable-chain-rule-backprop',
      'computational-graphs',
      'sigmoid-derivative',
      'relu-derivative',
      'softmax-gradient',
      'cross-entropy-gradient',
      'mse-gradient',
    ],
  },
  {
    id: 'probability-statistics',
    text: {
      title: { en: "1.3 Probability & Statistics", vi: "1.3 Probability & Statistics" },
      description: { en: "Probability, Bayes, random variables, distributions, and statistical estimation.", vi: "Xác suất, Bayes, biến ngẫu nhiên, phân phối và estimation." },
    },
    lessonIds: [
      'probability-basics',
      'joint-marginal-conditional',
      'independence',
      'law-total-probability',
      'bayes-theorem',
      'prior-likelihood-posterior',
      'bayesian-updating',
      'naive-bayes',
      'random-variables',
      'pmf-pdf-cdf',
      'expectation-variance-std',
      'covariance-correlation',
      'core-distributions',
      'poisson-exponential-multinomial',
      'central-limit-theorem',
      'law-large-numbers',
      'maximum-likelihood-estimation',
      'maximum-a-posteriori',
      'entropy-kl-cross-entropy',
    ],
  },
  {
    id: 'optimization',
    text: {
      title: { en: "1.4 Optimization", vi: "1.4 Optimization" },
      description: { en: "Loss functions, gradient descent, optimizers, training challenges, and regularization.", vi: "Loss, gradient descent, optimizer, vấn đề khi train và regularization." },
    },
    lessonIds: [
      'objective-loss-function',
      'convex-nonconvex-functions',
      'local-global-saddle',
      'constrained-optimization',
      'gradient-descent-intuition',
      'gradient-descent-update-rule',
      'learning-rate',
      'batch-sgd-minibatch',
      'momentum-optimizer',
      'rmsprop-optimizer',
      'adam-optimizer',
      'learning-rate-schedules',
      'vanishing-gradients',
      'exploding-gradients-clipping',
      'high-dimensional-saddle-points',
      'plateau-regions',
      'l2-regularization',
      'l1-regularization',
      'dropout-regularization',
      'early-stopping-regularization',
    ],
  },
  {
    id: 'information-theory',
    text: {
      title: { en: "1.5 Information Theory", vi: "1.5 Information Theory" },
      description: { en: "Entropy, cross-entropy, KL divergence, mutual information, bits, and nats.", vi: "Entropy, cross-entropy, KL divergence, mutual information, bit và nat." },
    },
    lessonIds: [
      'entropy-formula',
      'cross-entropy-loss',
      'kl-divergence',
      'mutual-information',
      'bits-vs-nats',
    ],
  },
];

export const learningTableOfContents = {
  id: 'math-statistics-ai',
  text: {
    title: { en: "Math & Statistics", vi: "Math & Statistics" },
    description: { en: "Learn the math that explains model behavior: vectors, matrices, gradients, probability, statistics, optimization, loss functions, entropy, and the intuition behind training signals.", vi: "Học phần toán giải thích hành vi model: vector, ma trận, gradient, xác suất, thống kê, tối ưu, loss function, entropy và trực giác phía sau tín hiệu training." },
  },
  status: 'active',
  chapters,
  sectionKinds: ['theory', 'calculation'],
} satisfies LearningTableOfContents;
