import type {
  LearningTableOfContents,
  LearningTocLessonSeed,
  LearningTocTrackSeed,
} from '../../../core/learning/types.ts';

// Each lessonSeed below is one node in the lesson table of contents.
// Concept panels inside a lesson are slides/steps, not TOC nodes.
const chapters: LearningTocTrackSeed[] = [
  {
    id: 'llm-from-scratch-orientation',
    text: {
      title: { en: "1.1 Overview", vi: "1.1 Tổng quan" },
      description: { en: "A TorchViz-native loop for learning LLM internals: theory, hand reasoning, then code.", vi: "Vòng học LLM internals theo kiểu TorchViz: lý thuyết, suy luận bằng tay, rồi code." },
    },
    lessonIds: [
      lessonSeed(
        'minimal-llm-project-skeleton',
        'Requirements',
        'Yêu cầu chuẩn bị',
      ),
      lessonSeed(
        'llm-from-scratch-roadmap',
        'The AI landscape',
        'Bức tranh tổng quan về AI',
      ),
      quizSeed('llm-component-checkpoint-quiz'),
      lessonSeed(
        'llm-system-components',
        'Components of an LLM system',
        'Các thành phần của hệ thống LLM',
      ),
      quizSeed('llm-system-components-quiz'),
      lessonSeed(
        'language-modeling-next-token',
        'Language modeling and next-token prediction',
        'Mô hình ngôn ngữ và dự đoán token tiếp theo',
      ),
      quizSeed('language-modeling-next-token-quiz'),
      lessonSeed(
        'ar-language-model-inference-pipeline',
        'AR language model inference pipeline',
        'Quy trình sinh token của AR Language Model',
      ),
      quizSeed('ar-language-model-inference-pipeline-quiz'),
      lessonSeed(
        'llm-output-head-and-loss',
        'Language model output head',
        'Output head của Language Model',
      ),
      quizSeed('llm-output-head-and-loss-quiz'),
      lessonSeed(
        'llm-next-token-loss',
        'Next-token loss during language-model training',
        'Loss function khi training Language Model',
      ),
      quizSeed('llm-next-token-loss-quiz'),
      lessonSeed(
        'llm-scale-and-development',
        'LLM scale and development',
        'Quy mô và sự phát triển của LLM',
      ),
      quizSeed('llm-scale-and-development-quiz'),
    ],
  },
  {
    id: 'text-data-and-tokenization',
    text: {
      title: { en: "1.2 Text Data & Tokenization", vi: "1.2 Text Data & Tokenization" },
      description: { en: "Raw text, token ids, context windows, batches, and the first dataloader.", vi: "Text thô, token id, context window, batch và dataloader đầu tiên." },
    },
    lessonIds: [
      lessonSeed(
        'text-embeddings-overview',
        'From raw text to embeddings',
        'Từ raw text đến embeddings',
      ),
      quizSeed('text-embeddings-overview-quiz'),
      lessonSeed(
        'tokenization-why-it-matters',
        'Why tokenization matters',
        'Tại sao dùng token thay vì chỉ dùng word?',
      ),
      quizSeed('tokenization-why-it-matters-quiz'),
      lessonSeed(
        'tokenizer-regex-from-scratch',
        'Code: Build a simple regex tokenizer',
        'Code: Xây tokenizer regex đơn giản',
      ),
      quizSeed('tokenizer-regex-from-scratch-quiz'),
      lessonSeed(
        'tokenization-bpe-tiktoken',
        'How tokenizer training works',
        'Huấn luyện tokenizer bằng BPE',
      ),
      quizSeed('tokenization-bpe-tiktoken-quiz'),
      lessonSeed(
        'tokenization-token-ids-vocabulary',
        'Token IDs and vocabulary',
        'Token IDs và vocabulary',
      ),
      quizSeed('tokenization-token-ids-vocabulary-quiz'),
      lessonSeed(
        'tokenization-raw-text-to-token-ids',
        'Worked example: Raw text to token IDs',
        'Worked example: Từ raw text đến token IDs',
      ),
      lessonSeed(
        'tokenization-special-tokens',
        'Special tokens',
        'Special tokens',
      ),
      quizSeed('tokenization-special-tokens-quiz'),
      lessonSeed(
        'sliding-window-and-embedding-calculation',
        'Sliding-window and batch calculation',
        'Tính sliding window và batch shape',
      ),
      quizSeed('token-counting-hand-quiz'),
      lessonSeed(
        'tokenizer-and-dataloader-code',
        'Tokenizer and dataloader code',
        'Code tokenizer và dataloader',
      ),
      lessonSeed(
        'tokenization-data-pipeline',
        'Token and positional embeddings',
        'Token embedding và positional embedding',
      ),
      quizSeed('tokenization-embedding-input-quiz'),
    ],
  },
  {
    id: 'attention-and-transformers-from-scratch',
    text: {
      title: { en: "1.3 Attention & Transformers From Scratch", vi: "1.3 Attention & Transformers From Scratch" },
      description: { en: "Causal masks, QKV shapes, attention scores, heads, and a minimal attention module.", vi: "Causal mask, shape QKV, attention score, head và module attention tối thiểu." },
    },
    lessonIds: [
      lessonSeed(
        'causal-self-attention-theory',
        'Causal self-attention theory',
        'Lý thuyết causal self-attention',
      ),
      quizSeed('attention-mechanism-checkpoint-quiz'),
      lessonSeed(
        'attention-score-shape-calculation',
        'Attention score and shape calculation',
        'Tính score và shape attention',
      ),
      lessonSeed(
        'multi-head-attention-theory',
        'Multi-head attention theory',
        'Lý thuyết multi-head attention',
      ),
      quizSeed('multi-head-attention-theory-quiz'),
      lessonSeed(
        'multi-head-attention-code',
        'Multi-head attention code',
        'Code multi-head attention',
      ),
    ],
  },
  {
    id: 'gpt-model-from-scratch',
    text: {
      title: { en: "1.4 GPT Model From Scratch", vi: "1.4 GPT Model From Scratch" },
      description: { en: "Decoder-only blocks, residual streams, normalization, MLPs, logits, and parameter checks.", vi: "Decoder-only block, residual stream, normalization, MLP, logits và kiểm tra parameter." },
    },
    lessonIds: [
      lessonSeed(
        'gpt-block-theory',
        'GPT block theory',
        'Lý thuyết GPT block',
      ),
      quizSeed('gpt-block-checkpoint-quiz'),
      lessonSeed(
        'gpt-parameter-shape-calculation',
        'GPT parameter and shape calculation',
        'Tính parameter và shape của GPT',
      ),
      lessonSeed(
        'gpt-module-code',
        'GPT module code',
        'Code module GPT',
      ),
    ],
  },
  {
    id: 'pretraining-and-generation',
    text: {
      title: { en: "1.5 Pretraining & Generation", vi: "1.5 Pretraining & Generation" },
      description: { en: "Next-token loss, perplexity, training loops, checkpoints, and autoregressive generation.", vi: "Next-token loss, perplexity, training loop, checkpoint và generation autoregressive." },
    },
    lessonIds: [
      lessonSeed(
        'llm-data-pipeline-overview',
        'Training and token generation overview',
        'Tổng quan quy trình huấn luyện và sinh token',
      ),
      quizSeed('llm-data-pipeline-checkpoint-quiz'),
      lessonSeed(
        'next-token-pretraining-theory',
        'Next-token pretraining theory',
        'Lý thuyết pretraining next-token',
      ),
      quizSeed('next-token-pretraining-theory-quiz'),
      lessonSeed(
        'loss-perplexity-hand-calculation',
        'Perplexity and LLM evaluation',
        'Perplexity và đánh giá LLM',
      ),
      quizSeed('benchmark-likelihood-quiz'),
      lessonSeed(
        'training-loop-and-generation-code',
        'Training loop and checkpoint code',
        'Code training loop và checkpoint',
      ),
      lessonSeed(
        'evaluation-beyond-perplexity',
        'Beyond Perplexity',
        'Beyond Perplexity',
      ),
      quizSeed('evaluation-beyond-perplexity-quiz'),
      lessonSeed(
        'generation-decoding-theory',
        'Generation and decoding theory',
        'Lý thuyết generation và decoding',
      ),
      quizSeed('generation-strategies-quiz'),
      lessonSeed(
        'generation-sampling-calculation',
        'Generation sampling calculation',
        'Tính temperature và top-k',
      ),
      lessonSeed(
        'generation-strategies-code',
        'Generation strategies code',
        'Code generation strategies',
      ),
    ],
  },
  {
    id: 'finetuning-and-alignment',
    text: {
      title: { en: "1.6 Fine-tuning & Alignment", vi: "1.6 Fine-tuning & Alignment" },
      description: { en: "Classification, instruction data, supervised fine-tuning, and preference-oriented thinking.", vi: "Classification, instruction data, supervised fine-tuning và tư duy theo preference." },
    },
    lessonIds: [
      lessonSeed(
        'finetuning-objectives-theory',
        'Fine-tuning objectives theory',
        'Lý thuyết objective fine-tuning',
      ),
      quizSeed('finetuning-objectives-theory-quiz'),
      lessonSeed(
        'classification-finetuning-theory',
        'Classification fine-tuning theory',
        'Lý thuyết classification fine-tuning',
      ),
      quizSeed('classification-finetuning-quiz'),
      lessonSeed(
        'classification-head-calculation',
        'Classification head calculation',
        'Tính classification head và loss',
      ),
      lessonSeed(
        'classification-finetuning-code',
        'Classification fine-tuning code',
        'Code classification fine-tuning',
      ),
      lessonSeed(
        'instruction-finetuning-theory',
        'Instruction fine-tuning theory',
        'Lý thuyết instruction fine-tuning',
      ),
      quizSeed('instruction-data-quality-quiz'),
      lessonSeed(
        'instruction-batch-mask-calculation',
        'Instruction batch and mask calculation',
        'Tính instruction batch và response mask',
      ),
      lessonSeed(
        'classification-and-instruction-finetune-code',
        'Instruction fine-tuning code',
        'Code instruction fine-tuning',
      ),
      lessonSeed(
        'lora-finetuning-theory',
        'LoRA fine-tuning theory',
        'Lý thuyết fine-tuning với LoRA',
      ),
      quizSeed('lora-finetuning-theory-quiz'),
      lessonSeed(
        'lora-minimal-code',
        'Minimal LoRA code',
        'Code LoRA tối thiểu',
      ),
    ],
  },
  {
    id: 'llm-fundamentals',
    text: {
      title: { en: "2.1 LLM Fundamentals", vi: "2.1 LLM Fundamentals" },
      description: { en: "Scaled transformer architecture, inference internals, training methods, preferences, and scaling laws.", vi: "Kiến trúc transformer ở scale lớn, inference internals, training, preference learning và scaling laws." },
    },
    lessonIds: [
      lessonSeed('transformer-at-scale', 'Transformer at scale', 'Transformer ở quy mô lớn'),
      quizSeed('transformer-at-scale-quiz'),
      lessonSeed('context-window-limits', 'Context-window limits', 'Giới hạn context window'),
      lessonSeed('kv-cache-inference', 'KV cache for inference', 'KV cache trong inference'),
      lessonSeed('tokenization-at-scale', 'Tokenization at scale', 'Tokenization ở quy mô lớn'),
      quizSeed('llm-pretraining'),
      lessonSeed('llm-positional-encodings', 'Positional encodings for LLMs', 'Positional encoding cho LLM'),
      quizSeed('llm-positional-encodings-quiz'),
      lessonSeed('flash-attention', 'FlashAttention and IO-aware attention', 'FlashAttention và IO-aware attention'),
      quizSeed('flash-attention-quiz'),
      lessonSeed('grouped-query-attention', 'Grouped-query attention', 'Grouped-query attention'),
      lessonSeed('sliding-window-attention', 'Sliding-window attention', 'Sliding-window attention'),
      lessonSeed('scaling-laws', 'Scaling laws and compute-optimal training', 'Scaling laws và compute-optimal training'),
      quizSeed('instruction-tuning'),
      lessonSeed('rlhf', 'RLHF: From preferences to a policy', 'RLHF: từ preference đến policy'),
      quizSeed('rlhf-quiz'),
      lessonSeed('constitutional-ai', 'Constitutional AI and preference learning', 'Constitutional AI và preference learning'),
      quizSeed('direct-preference-optimization'),
    ],
  },
  {
    id: 'llm-evaluation',
    text: {
      title: { en: "2.2 LLM Evaluation & Safety", vi: "2.2 LLM Evaluation & Safety" },
      description: { en: "Evaluation design, human and model judges, factuality, safety failure modes, guardrails, red teaming, and production regression testing.", vi: "Thiết kế evaluation, human và model judge, factuality, safety failure mode, guardrail, red teaming và regression test trong production." },
    },
    lessonIds: [
      lessonSeed('llm-evaluation-foundations', 'Why LLM evaluation is difficult', 'Vì sao đánh giá LLM khó?'),
      quizSeed('llm-evaluation-foundations-quiz'),
      lessonSeed('deterministic-and-reference-metrics', 'Deterministic and reference metrics', 'Deterministic checks và reference metrics'),
      quizSeed('evaluation-dataset-design'),
      lessonSeed('human-evaluation-rubrics', 'Human evaluation and rubrics', 'Human evaluation và rubric'),
      quizSeed('human-evaluation-rubrics-quiz'),
      lessonSeed('inter-rater-agreement', 'Inter-rater agreement', 'Độ đồng thuận giữa người chấm'),
      lessonSeed('pointwise-and-pairwise-evaluation', 'Pointwise and pairwise evaluation', 'Pointwise và pairwise evaluation'),
      lessonSeed('llm-as-a-judge', 'LLM as a judge', 'LLM-as-a-Judge'),
      quizSeed('llm-judge-biases'),
      lessonSeed('benchmark-selection-and-contamination', 'Benchmark selection and contamination', 'Chọn benchmark và contamination'),
      quizSeed('benchmark-selection-and-contamination-quiz'),
      lessonSeed('hallucination-and-factuality-evaluation', 'Hallucination and factuality evaluation', 'Đánh giá hallucination và factuality'),
      quizSeed('rag-evaluation'),
      lessonSeed('llm-safety-foundations', 'LLM safety foundations', 'Nền tảng LLM safety'),
      quizSeed('llm-safety-foundations-quiz'),
      lessonSeed('refusal-calibration', 'Refusal calibration', 'Hiệu chỉnh hành vi từ chối'),
      quizSeed('toxicity-bias-and-privacy'),
      lessonSeed('jailbreak-and-prompt-injection', 'Jailbreak and prompt injection', 'Jailbreak và prompt injection'),
      quizSeed('jailbreak-and-prompt-injection-quiz'),
      lessonSeed('guardrails-for-llm-applications', 'Guardrails for LLM applications', 'Guardrails cho ứng dụng LLM'),
      quizSeed('llm-red-teaming'),
      lessonSeed('production-regression-evals', 'Production regression evaluations', 'Regression evaluation trong production'),
      quizSeed('production-regression-evals-quiz'),
      lessonSeed('evaluation-ab-testing', 'Evaluation with A/B testing', 'A/B testing cho hệ thống LLM'),
      lessonSeed('evaluation-harness-code', 'Code: Build an evaluation harness', 'Code: Xây evaluation harness'),
    ],
  },
  {
    id: 'production-prompt-engineering',
    text: {
      title: { en: "2.3 Prompt Engineering", vi: "2.3 Prompt Engineering" },
      description: { en: "Prompt anatomy, prompting techniques, production constraints, injection defense, and prompt tools.", vi: "Cấu trúc prompt, kỹ thuật prompting, ràng buộc production, chống prompt injection và tooling." },
    },
    lessonIds: [
      lessonSeed('system-prompt', 'System instructions and trust boundaries', 'System instruction và trust boundary'),
      quizSeed('system-prompt-quiz'),
      lessonSeed('user-prompt', 'User input as untrusted data', 'User input như dữ liệu không tin cậy'),
      lessonSeed('assistant-turn-history', 'Assistant history and multi-turn state', 'Assistant history và state nhiều lượt'),
      quizSeed('role-prompting'),
      lessonSeed('zero-shot-prompting', 'Zero-shot with a minimal contract', 'Zero-shot với contract tối thiểu'),
      quizSeed('zero-shot-prompting-quiz'),
      lessonSeed('few-shot-examples', 'Purposeful few-shot examples', 'Few-shot examples có chủ đích'),
      quizSeed('one-shot-few-shot-prompting'),
      lessonSeed('clear-instruction-format-boundaries', 'Instruction, data, and format boundaries', 'Instruction, data và format boundaries'),
      quizSeed('clear-instruction-format-boundaries-quiz'),
      lessonSeed('examples-output-constraints', 'Examples and output constraints', 'Examples và output constraints'),
      quizSeed('prompt-negative-instructions'),
      lessonSeed('structured-output-prompting', 'Structured output: prompt, JSON mode, and schema', 'Structured output: prompt, JSON mode và schema'),
      quizSeed('structured-output-prompting-quiz'),
      lessonSeed('chain-of-thought', 'Verifiable reasoning without hidden chain of thought', 'Lập luận có thể kiểm chứng, không yêu cầu hidden CoT'),
      lessonSeed('self-consistency', 'Multi-sample verification and self-consistency', 'Multi-sample verification và self-consistency'),
      lessonSeed('react-prompting', 'Tool-use loops with the ReAct pattern', 'Vòng lặp tool use theo mẫu ReAct'),
      quizSeed('tree-of-thought'),
      lessonSeed('prompt-chaining', 'Prompt chaining with typed stages', 'Prompt chaining với typed stages'),
      quizSeed('prompt-chaining-quiz'),
      lessonSeed('prompt-compression', 'Verified prompt compression', 'Prompt compression có kiểm chứng'),
      lessonSeed('prompt-versioning-changelogs', 'Prompt versioning and changelogs', 'Versioning và changelog cho prompt'),
      lessonSeed('prompt-ab-testing', 'A/B testing prompts in production', 'A/B testing prompt trong production'),
      lessonSeed('prompt-injection-defense', 'Defense in depth for prompt injection', 'Prompt injection defense-in-depth'),
      lessonSeed('langsmith-observability', 'Observability for prompts and workflows', 'Observability cho prompt và workflow'),
      lessonSeed('openai-playground', 'Reproducible experiments in OpenAI Playground', 'Thí nghiệm tái lập trong OpenAI Playground'),
      lessonSeed('anthropic-console', 'Reproducible experiments in Anthropic Console', 'Thí nghiệm tái lập trong Anthropic Console'),
      quizSeed('promptlayer-tracking'),
    ],
  },
  {
    id: 'working-with-ai-apis',
    text: {
      title: { en: "2.4 Working with AI APIs", vi: "2.4 Working with AI APIs" },
      description: { en: "OpenAI, Anthropic, Gemini, Mistral, LLaMA, Ollama, and provider-specific API patterns.", vi: "OpenAI, Anthropic, Gemini, Mistral, LLaMA, Ollama và pattern API theo provider." },
    },
    lessonIds: [
      lessonSeed('chat-completions-api', 'Responses API and the Chat Completions migration path', 'Responses API và lộ trình từ Chat Completions'),
      quizSeed('chat-completions-api-quiz'),
      lessonSeed('function-calling-tool-use', 'Function calling and the tool-use contract', 'Function calling và tool-use contract'),
      lessonSeed('json-mode-structured-outputs', 'Structured Outputs versus JSON mode', 'Structured Outputs so với JSON mode'),
      lessonSeed('streaming-responses-sse', 'Streaming responses over SSE', 'Streaming response qua SSE'),
      lessonSeed('embeddings-api', 'Embeddings API and vector contracts', 'Embeddings API và vector contract'),
      lessonSeed('batch-api', 'Batch API and reconciliation', 'Batch API và reconciliation'),
      lessonSeed('token-counting-tiktoken', 'Token counting for the request envelope', 'Token counting cho request envelope'),
      quizSeed('rate-limits-quotas'),
      lessonSeed('vision-api-gpt4v', 'Multimodal inputs: Vision', 'Multimodal inputs: vision'),
      lessonSeed('assistants-api-file-search', 'File Search on Responses; migrate from Assistants', 'File Search trên Responses API; migrate từ Assistants'),
      lessonSeed('anthropic-messages-api', 'Anthropic Messages API', 'Anthropic Messages API'),
      quizSeed('anthropic-streaming'),
      lessonSeed('anthropic-system-prompts', 'System instructions in Anthropic Messages', 'System instruction trong Anthropic Messages'),
      lessonSeed('anthropic-long-context', 'Long-context budgeting with Anthropic', 'Long-context budgeting với Anthropic'),
      lessonSeed('anthropic-vision-support', 'Vision content blocks with Anthropic', 'Vision content blocks với Anthropic'),
      lessonSeed('anthropic-tool-use', 'Tool use with Anthropic', 'Tool use với Anthropic'),
      lessonSeed('gemini-models', 'Gemini Interactions API and model catalog', 'Gemini Interactions API và model catalog'),
      lessonSeed('gemini-multimodal-inputs', 'Gemini multimodal inputs', 'Gemini multimodal inputs'),
      lessonSeed('gemini-search-grounding', 'Grounding with Google Search', 'Grounding với Google Search'),
      lessonSeed('gemini-context-caching', 'Gemini context caching', 'Gemini context caching'),
      lessonSeed('mistral-models', 'Mistral Chat Completions and model catalog', 'Mistral Chat Completions và model catalog'),
      quizSeed('mistral-json-mode'),
      lessonSeed('mistral-function-calling', 'Function calling with Mistral', 'Function calling với Mistral'),
      lessonSeed('ollama-open-source-models', 'Choosing open models for Ollama', 'Chọn model mở cho Ollama'),
      quizSeed('peft-finetuning-llama'),
      lessonSeed('llama-3-models-api', 'Llama: Model cards, licenses, and serving contracts', 'Llama: model card, license và serving contract'),
      lessonSeed('ollama-local-llama', 'Local inference with Ollama', 'Local inference với Ollama'),
      lessonSeed('cohere-provider', 'Cohere provider capability delta', 'Cohere provider capability delta'),
      lessonSeed('nvidia-nim', 'NVIDIA NIM inference and management contracts', 'NVIDIA NIM inference và management contract'),
      lessonSeed('groq-inference', 'Groq inference and compatibility gaps', 'Groq inference và compatibility gaps'),
      lessonSeed('together-ai-hosting', 'Together AI hosting patterns', 'Together AI hosting patterns'),
      lessonSeed('replicate-hosting', 'Replicate prediction lifecycle', 'Replicate prediction lifecycle'),
    ],
  },
  {
    id: 'api-integration-patterns',
    text: {
      title: { en: "2.5 API Integration Patterns", vi: "2.5 API Integration Patterns" },
      description: { en: "Token limits, streaming, retries, queues, cost controls, caching, async work, and fallbacks.", vi: "Token limit, streaming, retry, queue, kiểm soát cost, cache, async work và fallback." },
    },
    lessonIds: [
      lessonSeed('context-window-management', 'Context-window management', 'Context-window management'),
      quizSeed('prompt-compression-cost-control'),
      lessonSeed('count-tokens-before-sending', 'Count tokens before dispatch', 'Đếm token trước khi gửi request'),
      lessonSeed('truncation-strategies', 'Purposeful truncation strategies', 'Truncation strategies có chủ đích'),
      lessonSeed('conversation-summarization', 'Conversation summarization with provenance', 'Conversation summarization có provenance'),
      lessonSeed('partial-response-handling', 'Handle partial responses', 'Xử lý partial response'),
      quizSeed('perceived-latency'),
      lessonSeed('sse-streaming-chunks', 'Normalize SSE chunks across providers', 'Chuẩn hóa SSE chunks giữa providers'),
      lessonSeed('client-stream-rendering', 'Safe client-side stream rendering', 'Rendering stream an toàn trên client'),
      lessonSeed('model-routing-by-complexity', 'Route models by capability and risk', 'Model routing theo capability và risk'),
      quizSeed('api-error-fallbacks'),
      lessonSeed('exponential-backoff-jitter', 'Exponential backoff with jitter', 'Exponential backoff với jitter'),
      lessonSeed('provider-quota-management', 'Provider quota management', 'Quản lý provider quota'),
      lessonSeed('queue-request-management', 'Queues and backpressure', 'Queue và backpressure'),
      lessonSeed('circuit-breaker-pattern', 'Circuit breakers for providers', 'Circuit breaker cho provider'),
      lessonSeed('token-usage-logging', 'Safe token-usage and cost observability', 'Token usage và cost observability an toàn'),
      lessonSeed('sha256-response-caching', 'Correctly scoped SHA-256 response caching', 'SHA-256 response caching đúng scope'),
      lessonSeed('async-pipelines', 'Asynchronous LLM pipelines', 'Async LLM pipelines'),
    ],
  },
  {
    id: 'secure-api-integration',
    text: {
      title: { en: "2.6 Secure API Integration", vi: "2.6 Secure API Integration" },
      description: { en: "API key safety, backend proxies, per-user rate limits, key rotation, logging, and monitoring.", vi: "Bảo vệ API key, backend proxy, rate limit theo user, key rotation, logging và monitoring." },
    },
    lessonIds: [
      lessonSeed('no-frontend-api-keys', 'Never put provider API keys in the frontend', 'Không đặt provider API key ở frontend'),
      quizSeed('no-frontend-api-keys-quiz'),
      lessonSeed('env-files-secret-manager', 'Environment variables and secret managers', 'Environment variables và secret managers'),
      lessonSeed('backend-proxy-pattern', 'A secure backend proxy for LLMs', 'Backend proxy an toàn cho LLM'),
      lessonSeed('redis-per-user-rate-limits', 'Per-user rate limits with Redis', 'Rate limit theo user với Redis'),
      lessonSeed('api-key-rotation', 'Rotate API keys without downtime', 'API key rotation không downtime'),
      quizSeed('logging-monitoring'),
    ],
  },
];

export const learningTableOfContents = {
  id: 'llm-ai-engineering',
  text: {
    title: { en: "LLMs", vi: "LLMs" },
    description: { en: "Study LLMs from internals to product use: token data, causal attention, GPT blocks, logits, generation, fine-tuning, alignment, evaluation, safety, prompt engineering, API integration, streaming, cost, and security patterns.", vi: "Học LLM từ internals đến sản phẩm: dữ liệu token, causal attention, GPT block, logits, generation, fine-tuning, alignment, evaluation, safety, prompt engineering, tích hợp API, streaming, cost và security pattern." },
  },
  status: 'active',
  fallbackLocales: ['vi'],
  chapters,
  sectionKinds: ['theory', 'code'],
} satisfies LearningTableOfContents;

function lessonSeed(
  id: string,
  titleEn: string,
  titleVi: string,
): LearningTocLessonSeed {
  return {
    id,
    title: { en: titleEn, vi: titleVi },
    status: 'available',
    contentStatus: 'published',
  };
}

function quizSeed(id: string): LearningTocLessonSeed {
  return lessonSeed(id, 'Quiz', 'Quiz');
}
