import type { LearningDomain, LearningLesson, LearningTrack } from '../types.ts';
import { buildPlaceholderContent, type LearningChapterSeed } from './seed.ts';

const chapters: LearningChapterSeed[] = [
  {
    id: 'llm-fundamentals',
    textKey: 'llmFundamentals',
    lessonIds: [
      'transformer-at-scale',
      'context-window-limits',
      'kv-cache-inference',
      'tokenization-at-scale',
      'llm-positional-encodings',
      'flash-attention',
      'grouped-query-attention',
      'sliding-window-attention',
      'llm-pretraining',
      'instruction-tuning',
      'rlhf',
      'constitutional-ai',
      'direct-preference-optimization',
      'scaling-laws',
    ],
  },
  {
    id: 'production-prompt-engineering',
    textKey: 'productionPromptEngineering',
    lessonIds: [
      'system-prompt',
      'user-prompt',
      'assistant-turn-history',
      'few-shot-examples',
      'zero-shot-prompting',
      'one-shot-few-shot-prompting',
      'chain-of-thought',
      'self-consistency',
      'react-prompting',
      'tree-of-thought',
      'structured-output-prompting',
      'role-prompting',
      'prompt-chaining',
      'clear-instruction-format-boundaries',
      'prompt-negative-instructions',
      'examples-output-constraints',
      'prompt-versioning-changelogs',
      'prompt-ab-testing',
      'prompt-compression',
      'prompt-injection-defense',
      'promptlayer-tracking',
      'langsmith-observability',
      'openai-playground',
      'anthropic-console',
    ],
  },
  {
    id: 'working-with-ai-apis',
    textKey: 'workingWithAiApis',
    lessonIds: [
      'chat-completions-api',
      'function-calling-tool-use',
      'json-mode-structured-outputs',
      'streaming-responses-sse',
      'embeddings-api',
      'vision-api-gpt4v',
      'assistants-api-file-search',
      'batch-api',
      'token-counting-tiktoken',
      'rate-limits-quotas',
      'anthropic-messages-api',
      'anthropic-system-prompts',
      'anthropic-long-context',
      'anthropic-vision-support',
      'anthropic-tool-use',
      'anthropic-streaming',
      'gemini-models',
      'gemini-multimodal-inputs',
      'gemini-search-grounding',
      'gemini-context-caching',
      'mistral-models',
      'mistral-function-calling',
      'mistral-json-mode',
      'ollama-open-source-models',
      'llama-3-models-api',
      'ollama-local-llama',
      'peft-finetuning-llama',
      'cohere-provider',
      'nvidia-nim',
      'groq-inference',
      'together-ai-hosting',
      'replicate-hosting',
    ],
  },
  {
    id: 'api-integration-patterns',
    textKey: 'apiIntegrationPatterns',
    lessonIds: [
      'count-tokens-before-sending',
      'truncation-strategies',
      'context-window-management',
      'conversation-summarization',
      'sse-streaming-chunks',
      'partial-response-handling',
      'client-stream-rendering',
      'perceived-latency',
      'exponential-backoff-jitter',
      'provider-quota-management',
      'queue-request-management',
      'circuit-breaker-pattern',
      'token-usage-logging',
      'model-routing-by-complexity',
      'prompt-compression-cost-control',
      'sha256-response-caching',
      'async-pipelines',
      'api-error-fallbacks',
    ],
  },
  {
    id: 'secure-api-integration',
    textKey: 'secureApiIntegration',
    lessonIds: [
      'no-frontend-api-keys',
      'env-files-secret-manager',
      'backend-proxy-pattern',
      'redis-per-user-rate-limits',
      'api-key-rotation',
      'logging-monitoring',
    ],
  },
];

const llmAiEngineeringContent = buildPlaceholderContent({
  domainId: 'llm-ai-engineering',
  domainTextKey: 'llmAiEngineering',
  domainStatus: 'active',
  chapters,
  sectionKinds: ['theory', 'code'],
});

export const llmAiEngineeringDomain: LearningDomain = llmAiEngineeringContent.domain;
export const llmAiEngineeringTracks: LearningTrack[] = llmAiEngineeringContent.tracks;
export const llmAiEngineeringLessons: LearningLesson[] = llmAiEngineeringContent.lessons;
