import type { LearningDomain, LearningLesson, LearningTrack } from '../types.ts';
import { buildPlaceholderContent, type LearningChapterSeed } from './seed.ts';

const chapters: LearningChapterSeed[] = [
  {
    id: 'linear-algebra',
    textKey: 'linearAlgebra',
    lessonIds: [
      'vectors-intuition',
      'vector-operations',
      'dot-product',
      'vector-norms',
      'unit-vectors-normalization',
      'cosine-similarity',
      'orthogonality',
      'matrix-operations',
      'elementwise-vs-matrix-product',
      'identity-inverse-matrix',
      'determinant-intuition',
      'matrix-rank',
      'linear-transformations',
      'systems-least-squares',
      'matrix-trace',
      'eigenvalues-eigenvectors',
      'pca-eigenvalues',
      'svd-intuition',
      'svd-dimensionality-reduction',
    ],
  },
  {
    id: 'calculus',
    textKey: 'calculus',
    lessonIds: [
      'derivative-intuition',
      'derivative-rules',
      'derivatives-log-exp-sigmoid',
      'minima-maxima-saddle',
      'second-derivative-convexity',
      'partial-derivatives',
      'gradient-vector',
      'gradient-descent-direction',
      'jacobian-matrix',
      'hessian-matrix',
      'single-variable-chain-rule',
      'multivariable-chain-rule-backprop',
      'computational-graphs',
      'sigmoid-derivative',
      'relu-derivative',
      'softmax-gradient',
      'cross-entropy-gradient',
      'mse-gradient',
    ],
  },
  {
    id: 'probability-statistics',
    textKey: 'probabilityStatistics',
    lessonIds: [
      'probability-basics',
      'joint-marginal-conditional',
      'independence',
      'law-total-probability',
      'bayes-theorem',
      'prior-likelihood-posterior',
      'bayesian-updating',
      'naive-bayes',
      'random-variables',
      'pmf-pdf-cdf',
      'expectation-variance-std',
      'covariance-correlation',
      'core-distributions',
      'poisson-exponential-multinomial',
      'central-limit-theorem',
      'law-large-numbers',
      'maximum-likelihood-estimation',
      'maximum-a-posteriori',
      'entropy-kl-cross-entropy',
    ],
  },
  {
    id: 'optimization',
    textKey: 'optimization',
    lessonIds: [
      'objective-loss-function',
      'convex-nonconvex-functions',
      'local-global-saddle',
      'constrained-optimization',
      'gradient-descent-intuition',
      'gradient-descent-update-rule',
      'learning-rate',
      'batch-sgd-minibatch',
      'momentum-optimizer',
      'rmsprop-optimizer',
      'adam-optimizer',
      'learning-rate-schedules',
      'vanishing-gradients',
      'exploding-gradients-clipping',
      'high-dimensional-saddle-points',
      'plateau-regions',
      'l2-regularization',
      'l1-regularization',
      'dropout-regularization',
      'early-stopping-regularization',
    ],
  },
  {
    id: 'information-theory',
    textKey: 'informationTheory',
    lessonIds: [
      'entropy-formula',
      'cross-entropy-loss',
      'kl-divergence',
      'mutual-information',
      'bits-vs-nats',
    ],
  },
];

const mathStatisticsAiContent = buildPlaceholderContent({
  domainId: 'math-statistics-ai',
  domainTextKey: 'mathStatisticsAi',
  domainStatus: 'active',
  chapters,
  sectionKinds: ['theory', 'calculation'],
});

export const mathStatisticsAiDomain: LearningDomain = mathStatisticsAiContent.domain;
export const mathStatisticsAiTracks: LearningTrack[] = mathStatisticsAiContent.tracks;
export const mathStatisticsAiLessons: LearningLesson[] = mathStatisticsAiContent.lessons;
