import type { LearningDomain, LearningLesson, LearningTrack } from '../types.ts';
import { buildPlaceholderContent, type LearningChapterSeed } from './seed.ts';

const chapters: LearningChapterSeed[] = [
  {
    id: 'data-management-versioning',
    textKey: 'dataManagementVersioning',
    lessonIds: [
      'dvc-data-version-control',
      'data-validation-great-expectations-pandera',
      'data-lineage',
      'feature-stores',
      'data-pipelines',
    ],
  },
  {
    id: 'experiment-tracking',
    textKey: 'experimentTracking',
    lessonIds: [
      'weights-biases-tracking',
      'mlflow-tracking',
      'experiment-tracking-fields',
      'comparing-runs-reporting',
    ],
  },
  {
    id: 'model-development-training-infrastructure',
    textKey: 'modelDevelopmentTrainingInfrastructure',
    lessonIds: [
      'gpu-cloud-training',
      'distributed-training',
      'mixed-precision-training',
      'model-checkpointing',
      'training-monitoring-alerting',
    ],
  },
  {
    id: 'model-evaluation-testing',
    textKey: 'modelEvaluationTesting',
    lessonIds: [
      'task-specific-benchmarks',
      'human-evaluation-guidelines',
      'llm-as-judge',
      'red-teaming',
      'model-ab-testing',
      'shadow-deployment',
      'canary-releases',
      'user-feedback-collection',
    ],
  },
  {
    id: 'model-deployment-serving',
    textKey: 'modelDeploymentServing',
    lessonIds: [
      'fastapi-ml-apis',
      'flask-ml-apis',
      'grpc-internal-services',
      'bentoml-serving',
      'ray-serve',
      'quantization-serving',
      'pruning-model-optimization',
      'knowledge-distillation',
      'onnx-model-format',
      'tensorrt-inference',
      'ollama-serving',
      'vllm-serving',
      'tgi-serving',
      'litellm-unified-api',
      'nvidia-nim-inference',
    ],
  },
  {
    id: 'containerization-orchestration',
    textKey: 'containerizationOrchestration',
    lessonIds: [
      'docker-containerization',
      'ml-service-dockerfile',
      'multi-stage-builds',
      'docker-compose-dev',
      'kubernetes-orchestration',
      'helm-charts',
      'horizontal-pod-autoscaler',
      'gpu-scheduling-k8s',
    ],
  },
  {
    id: 'cloud-deployment',
    textKey: 'cloudDeployment',
    lessonIds: [
      'aws-ec2-sagemaker',
      'aws-lambda-ai-functions',
      'aws-ecs-eks-containers',
      'aws-s3-model-data-storage',
      'aws-cloudwatch-monitoring',
      'gcp-vertex-ai',
      'gcp-cloud-run',
      'gcp-gke',
      'gcp-bigquery-ml-data',
      'azure-ml',
      'azure-openai-service',
      'azure-aks',
    ],
  },
  {
    id: 'monitoring-logging',
    textKey: 'monitoringLogging',
    lessonIds: [
      'token-usage-monitoring',
      'latency-percentiles',
      'provider-error-rates',
      'prompt-quality-monitoring',
      'response-quality-scores',
      'hallucination-detection',
      'behavior-drift-detection',
      'langsmith-monitoring',
      'helicone-analytics',
      'langfuse-observability',
      'prometheus-grafana',
      'datadog-monitoring',
      'sentry-error-tracking',
    ],
  },
  {
    id: 'ci-cd-for-ai',
    textKey: 'ciCdForAi',
    lessonIds: [
      'github-actions-gitlab-ci',
      'automated-ml-testing',
      'model-validation-before-deployment',
      'prompt-regression-testing',
      'automated-model-evaluation-ci',
      'ai-feature-flags',
      'blue-green-deployments',
    ],
  },
  {
    id: 'llm-security-safety',
    textKey: 'llmSecuritySafety',
    lessonIds: [
      'role-separation-security',
      'input-sanitization',
      'output-validation',
      'suspicious-prompt-logging',
      'file-injection-scanning',
      'openai-moderation-api',
      'input-pre-screening',
      'output-post-screening',
      'category-based-blocking',
      'custom-moderation-classifiers',
      'pii-detection-masking',
      'data-residency-requirements',
      'on-premise-deployment',
      'compliance-audit-logs',
    ],
  },
];

const mlopsLlmopsProductionSystemsContent = buildPlaceholderContent({
  domainId: 'mlops-llmops-production-systems',
  domainTextKey: 'mlopsLlmopsProductionSystems',
  domainStatus: 'active',
  chapters,
  sectionKinds: ['theory', 'code'],
});

export const mlopsLlmopsProductionSystemsDomain: LearningDomain = mlopsLlmopsProductionSystemsContent.domain;
export const mlopsLlmopsProductionSystemsTracks: LearningTrack[] = mlopsLlmopsProductionSystemsContent.tracks;
export const mlopsLlmopsProductionSystemsLessons: LearningLesson[] = mlopsLlmopsProductionSystemsContent.lessons;
