import type {
  LearningCitationEvidence,
  LearningCitationLinkOnlyException,
} from '../../../core/learning/citationEvidence.ts';

const climateGptLicenseUrl = 'https://creativecommons.org/licenses/by-sa/4.0/';

type ReviewedSourceSnippet = Omit<LearningCitationEvidence, 'id' | 'lessonId' | 'claimId' | 'paperId'>;

const reviewedAt = '2026-08-13';

function arxivHtml(
  arxivId: string,
  version: number,
  anchor: string,
  excerpt: string,
  searchText: string,
  locator = 'Abstract',
  reviewedDate = reviewedAt,
): ReviewedSourceSnippet {
  return {
    excerpt,
    searchText,
    locator,
    verificationUrl: `https://arxiv.org/html/${arxivId}v${version}#${anchor}`,
    targetPrecision: 'html-anchor',
    sourceVersion: `arXiv v${version}`,
    retrievedAt: reviewedDate,
    review: { status: 'verified', verifiedAt: reviewedDate },
    quotation: { basis: 'short-quotation' },
  };
}

function climateGptHtml(
  anchor: string,
  excerpt: string,
  searchText: string,
  locator: string,
): ReviewedSourceSnippet {
  return {
    ...arxivHtml('2401.09646', 1, anchor, excerpt, searchText, locator),
    quotation: { basis: 'redistributable-license', licenseUrl: climateGptLicenseUrl },
  };
}

function arxivLanding(
  arxivId: string,
  version: number,
  excerpt: string,
  searchText: string,
  locator = 'Abstract',
): ReviewedSourceSnippet {
  return {
    excerpt,
    searchText,
    locator,
    verificationUrl: `https://arxiv.org/abs/${arxivId}v${version}`,
    targetPrecision: 'landing-page',
    sourceVersion: `arXiv v${version}`,
    retrievedAt: reviewedAt,
    review: { status: 'verified', verifiedAt: reviewedAt },
    quotation: { basis: 'short-quotation' },
  };
}

function officialLanding(
  verificationUrl: string,
  excerpt: string,
  searchText: string,
  locator = 'Abstract',
  automatedAudit?: LearningCitationEvidence['automatedAudit'],
): ReviewedSourceSnippet {
  return {
    excerpt,
    searchText,
    locator,
    verificationUrl,
    targetPrecision: 'landing-page',
    retrievedAt: reviewedAt,
    review: { status: 'verified', verifiedAt: reviewedAt },
    quotation: { basis: 'short-quotation' },
    ...(automatedAudit ? { automatedAudit } : {}),
  };
}

function surveyParagraph(
  anchor: string,
  locator: string,
  excerpt: string,
  searchText: string,
): ReviewedSourceSnippet {
  return arxivHtml('2404.16789', 3, anchor, excerpt, searchText, locator);
}

const reviewedSourceSnippets: Readonly<Record<string, ReviewedSourceSnippet>> = {
  'overview-retrain-scaling-kaplan': arxivLanding('2001.08361', 1,
    'The loss scales as a power-law with model size, dataset size, and the amount of compute used for training',
    'scales as a power-law with model size, dataset size'),
  'overview-retrain-scaling-hoffmann': arxivLanding('2203.15556', 1,
    'for compute-optimal training, the model size and the number of training tokens should be scaled equally',
    'for compute-optimal training, the model size and the number of training tokens should be scaled equally'),
  'overview-vietnamese-adaptation-sailor': arxivLanding('2404.03608', 1,
    'Sailor models are continually pre-trained on diverse Southeast Asian languages',
    'diverse Southeast Asian languages'),
  'overview-vietnamese-adaptation-vimistral': arxivLanding('2403.15470', 1,
    'introduces an additional phase of continual pre-training, specifically adapted for Vietnamese',
    'additional phase of continual pre-training, specifically adapted for Vietnamese'),
  'overview-rag-external-context': climateGptHtml('S4.p2',
    'retrieving relevant documents from external databases and providing these documents as additional context to the model',
    'providing these documents as additional context to the model', '§4, đoạn 2'),
  'overview-domain-adaptation': surveyParagraph('S4.SS2.p1', '§4.2, đoạn 1',
    'facilitate effective adaptation of LLMs to downstream tasks',
    'effective adaptation of LLMs to downstream tasks'),
  'overview-retrieval-model-editing': surveyParagraph('S4.SS3.SSS4.p1', '§4.3.4, đoạn 1',
    'incorporate editing through retrieval mechanisms',
    'incorporate editing through retrieval mechanisms'),
  'overview-climategpt-cpt': climateGptHtml('S1.SS1.p4',
    'adapt an existing LLM trained on a large set of general domain data to the target domain',
    'adapt an existing LLM', '§1.1, Continued Pre-Training'),
  'overview-climategpt-ift': climateGptHtml('S1.SS1.p5',
    'inject instruction-following capabilities into the model',
    'inject instruction-following capabilities into the model', '§1.1, Instruction Fine-Tuning'),
  'overview-climategpt-rag': climateGptHtml('S1.SS1.p6',
    'implemented with high-quality climate resources to increase factuality as well as to extend the system with new knowledge',
    'implemented with high-quality climate resources', '§1.1, Retrieval Augmented Generation'),
  'overview-cl-goal': surveyParagraph('S1.p2', '§1, đoạn 2',
    'maintaining performance across all tasks',
    'maintaining performance across all tasks'),
  'survey-supplier-consumer-motivation': surveyParagraph('S1.p1', '§1, đoạn 1',
    'taking Twitter/X as an example, over 500 million new tweets were generated daily in 2023, training on even a subset of this vast amount of data could be financially unacceptable',
    '500 million'),
  van2022three: officialLanding(
    'https://www.nature.com/articles/s42256-022-00568-3',
    'To compare and contrast different continual learning methods, we identify three fundamental types or scenarios of incremental learning: task-incremental, domain-incremental and class-incremental learning.',
    'task-incremental, domain-incremental and class-incremental learning',
    'Abstract',
  ),
  'stability-plasticity-factor-01-gururangan': arxivLanding('2004.10964', 1,
    'a second phase of pretraining in-domain (domain-adaptive pretraining) leads to performance gains',
    'second phase of pretraining in-domain'),
  'stability-plasticity-factor-02-jin': arxivLanding('2110.08534', 2,
    'study a lifelong language model pretraining challenge where a PTLM is continually updated so as to adapt to emerging data',
    'continually updated so as to adapt to emerging data'),
  'stability-plasticity-factor-03-chaudhry': arxivLanding('1902.10486', 2,
    'continual learning where only a tiny episodic memory is present',
    'tiny episodic memory'),
  'stability-plasticity-factor-04-qi': arxivLanding('2310.03693', 1,
    'simply fine-tuning with benign and commonly used datasets can also inadvertently degrade the safety alignment of LLMs',
    'inadvertently degrade the safety alignment of LLMs'),
  mccloskey1989catastrophic: officialLanding(
    'https://www.sciencedirect.com/science/article/abs/pii/S0079742108605368',
    'New learning may interfere catastrophically with old learning when networks are trained sequentially.',
    'interfere catastrophically with old learning',
    'Publisher summary',
    { status: 'manual-required', reason: 'ScienceDirect returns HTTP 403 to the maintenance fetch; verify the publisher summary in a browser.' },
  ),
  wang2024comprehensive: arxivHtml('2302.00487', 3, 'abstract1.1',
    'the general objectives of continual learning as ensuring a proper stability-plasticity trade-off',
    'ensuring a proper stability-plasticity trade-off'),
  zheng2025spurious: arxivHtml('2501.13453', 1, 'abstract1.1',
    'such performance drops often reflect a decline in task alignment rather than knowledge loss',
    'a decline in task alignment rather than knowledge loss'),
  qin2023recyclable: arxivHtml('2305.08702', 1, 'abstract1.1',
    'proper algorithms for recycling outdated adapted weights should be developed',
    'recycling outdated adapted weights'),
  lopez2017gradient: arxivHtml('1706.08840', 6, 'S2.E3',
    'Backward transfer (BWT), which is the influence that learning a task t has on the performance on a previous task k≺t.',
    'Backward transfer (BWT), which is the influence that learning a task', '§2, Eq. 3'),
  chaudhry2019tiny: arxivHtml('1902.10486', 4, 'S3.SS2.SSS0.Px1.p1',
    'The average forgetting measure at task T is then defined as:',
    'The average forgetting measure at task', '§3.2, Eq. 2–3'),
  hinton2015distilling: arxivHtml('1503.02531', 1, 'S2.p1.1',
    'Neural networks typically produce class probabilities by using a “softmax” output layer that converts the logit',
    'produce class probabilities by using a “softmax” output layer', '§2, probabilities and logits', '2026-08-14'),
  romero2014fitnets: arxivHtml('1412.6550', 4, 'abstract1.1',
    'using not only the outputs but also the intermediate representations learned by the teacher as hints',
    'using not only the outputs but also the intermediate representations', 'Abstract', '2026-08-14'),
  li2017learning: arxivHtml('1606.09282', 3, 'abstract1.1',
    'uses only new task data to train the network while preserving the original capabilities',
    'uses only new task data to train the network', 'Abstract', '2026-08-14'),
  buzzega2020dark: arxivHtml('2004.07211', 2, 'S3.p1.3',
    'we retain the network’s logits, instead of the ground truth labels',
    'we retain the network’s logits', '§3, Dark Experience Replay', '2026-08-14'),
  'li2017learning-query-limits': arxivHtml('1606.09282', 3, 'S1.p9.1',
    'new task may provide a poor sampling of the original task domain',
    'may provide a poor sampling of the original task domain', '§1, LwF input limitation', '2026-08-14'),
  'buzzega2020dark-der-plus': arxivHtml('2004.07211', 2, 'S3.p3.1',
    'logits that are highly biased by the training on previous tasks',
    'logits that are highly biased by the training on previous tasks', '§3, DER++', '2026-08-14'),
  shi2024unified: arxivHtml('2310.12244', 1, 'S3.SS1.p2.1',
    'naively using ERM to learn is equivalent to minimizing a loose generalization bound',
    'equivalent to minimizing a loose generalization bound', '§3.1, Lemma 3.1 discussion'),
  wistuba2023: arxivHtml('2311.17601', 1, 'S2.SS2.SSS0.Px2.p1.1',
    'At inference time for an instance, we estimate the cluster center which is nearest to it.',
    'we estimate the cluster center which is nearest', '§2.2, task inference'),
  kirkpatrick2017overcoming: arxivHtml('1612.00796', 2, 'abstract1.1',
    'remembers old tasks by selectively slowing down learning on the weights important for those tasks',
    'selectively slowing down learning on the weights important for those tasks'),
  zenke2017continual: officialLanding('https://proceedings.mlr.press/v70/zenke17a.html',
    'Each synapse accumulates task relevant information over time, and exploits this information to rapidly store new memories without forgetting old ones.',
    'Each synapse accumulates task relevant information over time'),
  kim2022theoretical: officialLanding('https://proceedings.neurips.cc/paper_files/paper/2022/hash/20f44da80080d76bbc35bca0027f14e6-Abstract-Conference.html',
    'There are two popular CL settings, class incremental learning (CIL) and task incremental learning (TIL).',
    'class incremental learning (CIL) and task incremental learning (TIL)'),
  jin2022lifelong: arxivHtml('2110.08534', 3, 'abstract1.1',
    'adapt to new corpora while retaining learned knowledge in earlier corpora',
    'retaining learned knowledge in earlier corpora'),
  qin2022elle: officialLanding('https://aclanthology.org/2022.findings-acl.220/',
    'ELLE consists of (1) function preserved model expansion, which flexibly expands an existing PLM’s width and depth',
    'function preserved model expansion'),
  amba2021dynamic: arxivHtml('2106.06297', 1, 'abstract1.1',
    'how these language models can be adapted to better handle continuously evolving web content',
    'adapted to better handle continuously evolving web content'),
  xie2023efficient: arxivHtml('2311.08545', 2, 'abstract1.1',
    'outperform vanilla continual pre-training’s performance with just 10% of corpus size and cost',
    'with just 10% of corpus size and cost'),
  yildiz2024investigating: arxivHtml('2402.17400', 2, 'S2.SS0.SSS0.Px2.p2.1',
    'Ultimately, we utilized 159 domains in our study.',
    'we utilized 159 domains in our study', '§2, corpus domains'),
  li2024examining: arxivHtml('2401.03129', 1, 'abstract1.1',
    'evaluate the impact of continuous pre-training on the fine-tuned LLM across various dimensions, including output format, knowledge, and reliability',
    'including output format, knowledge, and reliability'),
  gupta2023continual: arxivHtml('2308.04014', 2, 'abstract1.1',
    'while rewarming models first increases the loss on upstream and downstream data, in the longer run it improves the downstream performance',
    'in the longer run it improves the downstream performance'),
  ibrahim2024simple: arxivHtml('2403.08763', 4, 'abstract1.1',
    'a simple and scalable combination of learning rate (LR) re-warming, LR re-decaying, and replay of previous data',
    're-warming, LR re-decaying, and replay of previous data'),
  gururangan2022demix: arxivHtml('2108.05036', 2, 'abstract1.1',
    'experts can be added to iteratively incorporate new domains without forgetting older ones',
    'incorporate new domains without forgetting older ones'),
  chen2023lifelong: arxivHtml('2305.12281', 1, 'abstract1.1',
    'Lifelong-MoE, an extensible MoE architecture that dynamically adds model capacity via adding experts with regularized pretraining',
    'dynamically adds model capacity via adding experts'),
  cossu2022continual: arxivHtml('2205.09357', 1, 'abstract1.1',
    'continually pre-trained models are robust against catastrophic forgetting',
    'robust against catastrophic forgetting'),
  jang2022towards: arxivHtml('2110.03215', 4, 'S1.p4.1',
    'retention of time-invariant world knowledge, the update of outdated knowledge, and the acquisition of new knowledge',
    'the update of outdated knowledge, and the acquisition of new knowledge', '§1, CKL formulation'),
  jang2022temporalwiki: officialLanding('https://aclanthology.org/2022.emnlp-main.418/',
    'utilizes the difference between consecutive snapshots of English Wikipedia and English Wikidata for training and evaluation',
    'the difference between consecutive snapshots of English Wikipedia'),
  dhingra2022time: arxivHtml('2106.15110', 2, 'abstract1.1',
    'a simple technique for jointly modeling text with its timestamp',
    'jointly modeling text with its timestamp'),
  zhao2024large: arxivHtml('2404.08707', 7, 'abstract1.1',
    'the Continue Evolving from Mistakes (CEM) method, a data-efficient approach',
    'Continue Evolving from Mistakes'),
  lin2024rho: arxivHtml('2404.07965', 4, 'abstract1.1',
    'selectively trains on useful tokens that aligned with the desired distribution',
    'selectively trains on useful tokens'),
  chen2024take: arxivHtml('2402.14270', 2, 'abstract1.1',
    'dynamically prioritize the training focus on informative samples through an instance reweighting mechanism',
    'prioritize the training focus on informative samples'),
  loureiro2022timelms: officialLanding('https://aclanthology.org/2022.acl-demo.25/',
    'a continual learning strategy contributes to enhancing Twitter-based language models’ capacity to deal with future and out-of-distribution tweets',
    'deal with future and out-of-distribution tweets'),
  attanasio2023worth: arxivHtml('2210.07365', 2, 'abstract1.1',
    'Pretrained models without temporal adaptation are actually significantly more effective and efficient.',
    'significantly more effective and efficient'),
  gururangan2020dont: officialLanding('https://aclanthology.org/2020.acl-main.740/',
    'a second phase of pretraining in-domain (domain-adaptive pretraining) leads to performance gains',
    'domain-adaptive pretraining) leads to performance gains'),
  colombo2024saullm7b: arxivHtml('2403.03883', 2, 'abstract1.1',
    'SaulLM-7B is trained on an English legal corpus of over 30 billion tokens',
    'over 30 billion tokens'),
  xie2024me: arxivLanding('2402.12749', 5,
    'developed through continued pre-training and instruction tuning with 129B tokens and 214K samples',
    'continued pre-training and instruction tuning with 129B tokens'),
  Chen2023HuatuoGPTII: arxivHtml('2311.09774', 2, 'abstract1.1',
    'a one-stage domain adaption protocol where heterogeneous data from both the traditional pre-training and supervised stages are unified',
    'a one-stage domain adaption protocol'),
  yan2023af: arxivHtml('2211.11363', 2, 'abstract1.1',
    'with only about 17% of model parameters trained, AF Adapter achieves 0.6%, 2% gain in performance on average',
    'AF Adapter achieves 0.6%, 2% gain'),
  Lu2023BBTFin: arxivHtml('2302.09432', 2, 'S2.T1.2.6.3',
    '80B tokens', '80B tokens', '§2, Table 1'),
  li2023cfgpt: arxivHtml('2309.10654', 2, 'abstract1.1',
    '584M documents and 141B tokens in total',
    '141B tokens in total'),
  Zhang2023xuanyuan: arxivHtml('2305.12002', 1, 'S3.SS2.p1.1',
    'it integrates data from both general and financial domains',
    'integrates data from both general and financial domains', '§3.2'),
  Bi2023OCEANGPT: arxivHtml('2310.02031', 8, 'abstract1.1',
    'OceanGPT, the first-ever large language model in the ocean domain',
    'large language model in the ocean domain'),
  deng2023learning: arxivHtml('2306.05064', 2, 'abstract1.1',
    'further train the LLaMA-7B model on 5.5B tokens of geoscience text corpus',
    '5.5B tokens of geoscience text corpus'),
  Nguyen2023AstroLLaMA: arxivHtml('2309.06126', 1, 'abstract1.1',
    'fine-tuned from LLaMA-2 using over 300,000 astronomy abstracts from arXiv',
    'over 300,000 astronomy abstracts'),
  Zheng2023MarineGPT: arxivHtml('2310.13596', 1, 'abstract1.1',
    'MarineGPT, the first vision-language model specially designed for the marine domain',
    'vision-language model specially designed for the marine domain'),
  thulke2024climategpt: arxivHtml('2401.09646', 1, 'abstract1.1',
    'continuously pre-trained from Llama 2 on a domain-specific dataset of 4.2B tokens',
    'domain-specific dataset of 4.2B tokens'),
  lin2023geogalactica: arxivHtml('2401.00434', 2, 'abstract1.1',
    'further pre-training the model with a vast amount of texts in geoscience',
    'further pre-training the model with a vast amount of texts in geoscience'),
  Azerbayev2023LLEMMA: arxivLanding('2310.10631', 3,
    'continue pretraining Code Llama on the Proof-Pile-2, a mixture of scientific papers, web data containing mathematics, and mathematical code',
    'continue pretraining Code Llama on the Proof-Pile-2'),
  Yang2023PLLaMa: arxivHtml('2401.01600', 1, 'abstract1.1',
    'enhanced with a comprehensive database, comprising more than 1.5 million scholarly articles in plant science',
    'more than 1.5 million scholarly articles in plant science'),
  'rozière2024code': arxivHtml('2308.12950', 3, 'S2.SS2.p1.1',
    'To help the model retain natural language understanding skills, we also sample a small proportion of our batches from a natural language dataset.',
    'retain natural language understanding skills', '§2.2'),
  paul2024ircoder: arxivHtml('2403.03894', 3, 'abstract1.1',
    'leveraging readily available compiler intermediate representations (IR)—shared across programming languages',
    'compiler intermediate representations (IR)'),
  wu2024llama: arxivHtml('2401.02415', 2, 'abstract1.1',
    'a new post-pretraining method for LLMs with an expansion of Transformer blocks',
    'expansion of Transformer blocks'),
  han2021econet: officialLanding('https://aclanthology.org/2021.emnlp-main.436/',
    'self-supervised learning objectives to recover masked-out event and temporal indicators',
    'recover masked-out event and temporal indicators'),
  zhou2020pre: arxivHtml('2011.07956', 2, 'abstract1.1',
    'generative and contrastive objectives for learning common sense from the text',
    'generative and contrastive objectives'),
  cheng2024adapting: arxivHtml('2309.09530', 4, 'abstract1.1',
    'transforming raw corpora into reading comprehension texts',
    'transforming raw corpora into reading comprehension texts'),
  shen2024tag: arxivHtml('2402.05140', 3, 'abstract1.1',
    'domain tags are used to delimit specialized representations',
    'domain tags are used to delimit specialized representations'),
  nakamura2024aurora: arxivHtml('2404.00399', 3, 'abstract1.1',
    'Continually pretrained from StarCoderPlus on 435B additional tokens',
    '435B additional tokens'),
  fujii2024continual: arxivHtml('2404.17790', 1, 'abstract1.1',
    'extending the vocabulary of Llama 2 to include Japanese characters and conducting continual pre-training on a large Japanese web corpus',
    'conducting continual pre-training on a large Japanese web corpus'),
  dou2024sailor: arxivHtml('2404.03608', 1, 'abstract1.1',
    'small proxy models to optimize data mixture',
    'small proxy models to optimize data mixture'),
  zhao2024sapt: arxivHtml('2401.08295', 3, 'abstract1.1',
    'align the PET learning and selection via the Shared Attentive Learning & Selection module',
    'Shared Attentive Learning & Selection module'),
  das2024larimar: arxivHtml('2403.11901', 4, 'abstract1.1',
    'a novel, brain-inspired architecture for enhancing LLMs with a distributed episodic memory',
    'a distributed episodic memory'),
  mehta2023empirical: arxivHtml('2112.09153', 2, 'abstract1.1',
    'pre-trained weights appear to ease forgetting by leading to wider minima',
    'ease forgetting by leading to wider minima'),
  zheng2023learn: arxivHtml('2312.07887', 5, 'abstract1.1',
    'most of them severely underestimate the inherent anti-forgetting ability of PLMs',
    'inherent anti-forgetting ability of PLMs'),
  winata2023overcoming: arxivHtml('2305.16252', 1, 'abstract1.1',
    'LR ADJUST, a learning rate scheduling method that is simple, yet effective in preserving new information without strongly overwriting past knowledge',
    'without strongly overwriting past knowledge'),
  qin2021lfpt5: arxivHtml('2110.07298', 3, 'abstract1.1',
    'LFPT5 generates pseudo (labeled) samples of previously learned domains',
    'generates pseudo (labeled) samples of previously learned domains'),
  chen2024parameterizing: arxivHtml('2310.04801', 1, 'abstract1.1',
    'integrating parameter-efficient fine-tuning (PEFT) and in-context tuning (ICT)',
    'parameter-efficient fine-tuning (PEFT) and in-context tuning (ICT)'),
  scialom2022fine: arxivHtml('2205.12393', 4, 'abstract1.1',
    'Continual-T0 (CT0) is able to learn 8 new diverse language generation tasks, while still maintaining good performance on previous tasks',
    'maintaining good performance on previous tasks'),
  he2024dont: arxivHtml('2403.10056', 4, 'abstract1.1',
    'computes the information gain on masked parts to dynamically replay data and refine the training objective',
    'dynamically replay data and refine the training objective'),
  huang2024mitigating: arxivHtml('2403.01244', 2, 'abstract1.1',
    'Self-Synthesized Rehearsal (SSR) that uses the LLM to generate synthetic instances for rehearsal',
    'generate synthetic instances for rehearsal'),
  mok2023large: officialLanding('https://aclanthology.org/2023.acl-long.703/',
    'DynaInst, the proposed method to lifelong in-context instruction learning, achieves noticeable improvements',
    'DynaInst, the proposed method'),
  wang2023orthogonal: arxivHtml('2310.14152', 1, 'abstract1.1',
    'learns tasks in different (low-rank) vector subspaces that are kept orthogonal to each other',
    'kept orthogonal to each other'),
  hu2024wilke: arxivHtml('2402.10987', 2, 'abstract1.1',
    'selects editing layer based on the pattern matching degree of editing knowledge across different layers',
    'selects editing layer based on the pattern matching degree'),
  wang2024wise: arxivHtml('2405.14768', 3, 'abstract1.1',
    'a dual parametric memory scheme, which consists of the main memory for the pretrained knowledge and a side memory for the edited knowledge',
    'main memory for the pretrained knowledge and a side memory'),
  hase2023does: arxivHtml('2301.04213', 2, 'abstract1.1',
    'which model MLP layer would be best to edit in order to override an existing stored fact',
    'best to edit in order to override an existing stored fact'),
  zhang2023copf: arxivHtml('2310.15694', 5, 'abstract1.1',
    'regularize the current policy based on the historically optimal distribution to mitigate Catastrophic Forgetting',
    'historically optimal distribution to mitigate Catastrophic Forgetting'),
  zhai2023investigating: arxivHtml('2309.10313', 4, 'abstract1.1',
    'almost all evaluated MLLMs fail to retain the same performance levels as their vision encoders',
    'fail to retain the same performance levels'),
  zheng2024antiforgetting: arxivHtml('2401.09181', 3, 'abstract1.1',
    'projects the prompt gradient to the residual space to minimize interference between tasks',
    'minimize interference between tasks'),
  petroni2019language: arxivHtml('1909.01066', 2, 'abstract1.1',
    'queries structured as “fill-in-the-blank” cloze statements',
    'fill-in-the-blank'),
  wang2023trace: arxivHtml('2310.06762', 1, 'S1.p3.1',
    'three metrics: ”General Ability Delta,” ”Instruction Following Delta,” and ”Safety Delta”',
    'General Ability Delta', '§1, evaluation dimensions'),
  yang2024reawakening: arxivHtml('2403.09613', 2, 'abstract1.1',
    'recovering from the forgetting on documents before encountering them again',
    'before encountering them again'),
  jin2024model: arxivHtml('2402.01865', 3, 'abstract1.1',
    'forecast upstream examples that will be forgotten due to a model update',
    'forecast upstream examples that will be forgotten'),
  ramsauer2021hopfield: arxivHtml('2008.02217', 3, 'abstract1.1',
    'can store exponentially many patterns, retrieves the pattern with one update',
    'retrieves the pattern with one update'),
  lu2023ibcl: arxivLanding('2310.02995', 3,
    'models obtained by IBCL have guarantees in identifying the Pareto optimal parameters',
    'guarantees in identifying the Pareto optimal parameters'),
  'wang2024comprehensive-taxonomy': arxivHtml('2302.00487', 3, 'S1.p3.1',
    'can be conceptually separated into five groups',
    'conceptually separated into five groups', '§1, taxonomy overview'),
  'wang2024comprehensive-taylor': arxivHtml('2302.00487', 3, 'S3.SS2.p2.1',
    'the maximum sacrifice of its performance can be estimated by performing a second-order Taylor expansion',
    'maximum sacrifice of its performance can be estimated', '§3.2, generalizability analysis'),
  'zheng2025spurious-biography': arxivHtml('2501.13453', 1, 'S3.p1.1',
    'we constructed a synthetic dataset, the Biography dataset, and designed controlled experiments to investigate the underlying causes of spurious forgetting',
    'constructed a synthetic dataset, the Biography dataset', '§3, controlled experiments'),
  'qin2023recyclable-supplier': arxivHtml('2305.08702', 1, 'S1.p2.1',
    'PLMs may constantly get upgraded and released by the supplier. Correspondingly, the customer-side compatible update of adapted weights becomes necessary.',
    'released by the supplier', '§1, supplier–consumer update'),
  'wistuba2023-overview': arxivHtml('2311.17601', 1, 'S2.p1.1',
    'present our method Continual Low Rank Adaptation (CoLoR)',
    'Continual Low Rank Adaptation (CoLoR)', '§2'),
  'wistuba2023-frozen-lora': arxivHtml('2311.17601', 1, 'S2.SS2.SSS0.Px1.p1.1',
    'the parameters of h are frozen but it is extended by dataset-specific LoRA modules',
    'frozen but it is extended by dataset-specific LoRA modules', '§2.2, training'),
  'takahashi2024pretraining-rag-evaluation': arxivHtml('2404.08262', 3, 'S1.p5.1',
    'three tasks whose inputs are 1) question-only, 2) question with automatically retrieved context, and 3) question with manually retrieved context',
    'question with automatically retrieved context', '§1, benchmark design'),
  'wang2023trace-gsm8k': arxivHtml('2310.06762', 1, 'abstract1.1',
    'the accuracy of llama2-chat 13B on gsm8k dataset declined precipitously from 28.8% to 2% after training on our datasets',
    'declined precipitously from 28.8% to 2%', 'Abstract'),
  'huang2023lawyer-replay': arxivHtml('2305.15062', 2, 'S2.SS1.p2.1',
    'for sparse episodic replay',
    'for sparse episodic replay', '§2.1, continual training data'),
  'guo2023continuous-tradeoff': arxivHtml('2311.00204', 1, 'S3.SS2.p2.1',
    'the model accuracy on CMExam tends to increase as continual training progresses. However, decreases are observed in the MMLU and CMMLU metrics over time',
    'decreases are observed in the MMLU and CMMLU metrics over time', '§3.2, Table 3 discussion'),
  'mehta2023empirical-sam': arxivHtml('2112.09153', 2, 'S1.I1.i4.p1.1',
    'explicitly seeking flat minima during task incremental learning leads to reduced forgetting',
    'explicitly seeking flat minima', '§1, contribution 4'),
  'zheng2023learn-seq': arxivHtml('2312.07887', 5, 'S4.SS1.p3.1',
    '(S1) Freeze the PLMs after warm-up; (S2) Freeze the old classifiers when learning new tasks',
    'Freeze the PLMs after warm-up', '§4.1, SEQ* strategies'),
  'ke2021achieve-modules': arxivHtml('2112.02706', 1, 'S4.SS2.p2.1',
    'Each layer’s output is further applied with a task mask to indicate which neurons should be protected for that task',
    'task mask to indicate which neurons should be protected', '§4.2, task-specific module'),
  'lin2024mitigating-hma': arxivHtml('2309.06256', 4, 'abstract1.2',
    'we propose Heterogeneous Model Averaging (HMA) to Heterogeneously find various combination ratios of model layers',
    'various combination ratios of model layers', 'Abstract'),
  'yin2022contintin-strategies': arxivHtml('2203.08512', 2, 'S1.p4.1',
    'The second strategy, “History Training”, revisits instructions of earlier tasks during continual learning to alleviate the catastrophic forgetting issue in backward-transfer.',
    'revisits instructions of earlier tasks', '§1, InstructionSpeak strategies'),
  'hartvigsen2023aging-key-value': arxivHtml('2211.11031', 5, 'S2.SS2.SSS0.Px2.p1.2',
    'h can be seen as a query to the codebook, and GRACE retrieves the value associated with its closest key',
    'retrieves the value associated with its closest key', '§2.2, deferral mechanism'),
  'yu2023melo-vector-database': arxivHtml('2312.11795', 1, 'Sx1.p3.1',
    'MELO alters the behavior of language models by dynamically activating certain blocks of low-rank adapter (LoRA) according to the index built in an inner vector database',
    'index built in an inner vector database', 'Introduction'),
  'he2023continual-expansion': arxivHtml('2311.16206', 1, 'S1.p6.1',
    'we expand the projection layer for each new task as a task-specific module and freeze all other modules to prevent forgetting',
    'expand the projection layer for each new task', '§1, model-expansion setup'),
  'zhu2024model-patch': arxivHtml('2402.12048', 1, 'abstract1.1',
    'replacing a small number (≤10%) of fine-tuned parameters',
    'fine-tuned parameters', 'Abstract'),
  'zhao2024reconstruct-components': arxivHtml('2403.11373', 1, 'S1.I1.i3.p1.1',
    'decompose prompts into modality-specific components and explicitly harness the multi-modal knowledge from a pre-trained model to reconstruct the absent query',
    'reconstruct the absent query', '§1, contribution 3'),
  'chen2024coin-experts': arxivHtml('2403.08350', 2, 'S5.p1.1',
    'utilize experts to acquire distinct knowledge for different tasks to mitigate forgetting',
    'experts to acquire distinct knowledge for different tasks', '§5'),
  'survey-vertical-horizontal': surveyParagraph('S1.p3.2', '§1, hai hướng continuity',
    'Recyclable Tuning preserves both vertical and horizontal continuity simultaneously',
    'preserves both vertical and horizontal continuity'),
  'survey-method-taxonomy': surveyParagraph('S2.SS2.SSS2.p1.1', '§2.2.2, đoạn 1',
    'Existing CL techniques can be roughly categorized into five groups',
    'categorized into five groups'),
  'survey-cl-retention': surveyParagraph('S1.p2.1', '§1, đoạn 2',
    'trains machine learning models sequentially on a series of tasks with the expectation of maintaining performance across all tasks',
    'maintaining performance across all tasks'),
  'survey-llm-challenges': surveyParagraph('S3.p1.1', '§3, đoạn 1',
    'The substantial scale of LLMs presents notable challenges for development teams',
    'substantial scale of LLMs presents notable challenges'),
  'survey-settings': surveyParagraph('S2.SS2.SSS1.p1.1', '§2.2.1, đoạn 1',
    'Class-Incremental Learning (CIL), where the model learns new classes of data during training',
    'model learns new classes of data during training'),
  'survey-replay': surveyParagraph('S2.SS2.SSS2.p2.1', '§2.2.2, đoạn 2',
    'keeping a small buffer of observed data and retraining the model on it when learning new tasks',
    'keeping a small buffer of observed data'),
  'survey-regularization': surveyParagraph('S2.SS2.SSS2.p2.1', '§2.2.2, đoạn 2',
    'a regularization term that penalizes large deviation from the history model in the parameter space',
    'penalizes large deviation from the history model'),
  'survey-architecture': surveyParagraph('S2.SS2.SSS2.p2.1', '§2.2.2, đoạn 2',
    'can achieve zero-forgetting when task IDs are available during inference or can be correctly inferred',
    'when task IDs are available during inference'),
  'survey-learning-stages': surveyParagraph('S1.p4.1', '§1, đoạn 4',
    'three key stages of LLM learning within modern CL: Continual Pre-Training (CPT), Domain-Adaptive Pre-training (DAP), and Continual Fine-Tuning (CFT)',
    'Continual Pre-Training (CPT), Domain-Adaptive Pre-training (DAP), and Continual Fine-Tuning (CFT)'),
  'survey-vertical': surveyParagraph('S3.SS1.p1.1', '§3.1, đoạn 1',
    'the training task transitions gradually from general pre-training to downstream tasks',
    'transitions gradually from general pre-training to downstream tasks'),
  'survey-vertical-distribution-coverage': surveyParagraph('S3.SS1.p1.1', '§3.1, đoạn 1',
    'the upstream data distribution usually partially covers the subsequent tasks\' data distribution',
    'upstream data distribution usually partially covers'),
  'survey-vertical-two-challenges': surveyParagraph('S3.SS1.p1.1', '§3.1, hai thách thức',
    'there are two primary challenges to be resolved: Task Heterogeneity and Inaccessible Upstream Data',
    'two primary challenges to be resolved: Task Heterogeneity and Inaccessible Upstream Data'),
  'survey-upstream-data': surveyParagraph('S3.I2.i2.p1.1', '§3.1, inaccessible upstream data',
    'existing methods either use public datasets or generate pseudo-examples to create proxy pre-training datasets',
    'use public datasets or generate pseudo-examples'),
  'survey-horizontal': surveyParagraph('S3.SS2.p1.1', '§3.2, đoạn 1',
    'Horizontal continual learning of LLMs involves learning sequentially across different domains or time steps within the same stage',
    'Horizontal continual learning of LLMs involves learning sequentially'),
  'survey-horizontal-abrupt': surveyParagraph('S3.I3.i2.p1.1', '§3.2, abrupt distributional shift',
    'abrupt changes in task distributions can result in significant horizontal forgetting',
    'significant horizontal forgetting'),
  'survey-horizontal-two-challenges': surveyParagraph('S3.SS2.p1.2', '§3.2, hai thách thức',
    'Long Task Sequences and Abrupt Distributional Shift pose severe challenges for horizontal continual learning',
    'Long Task Sequences'),
  'survey-cpt-pipeline': surveyParagraph('S4.SS1.SSS1.p1.1', '§4.1.1, đoạn 1',
    'when distributional shifts are gradual or somewhat correlated, CPT can effectively help model generalize to unseen data',
    'CPT can effectively help model generalize to unseen data'),
  'survey-cpt-efficiency': surveyParagraph('S4.SS1.SSS1.p1.1', '§4.1.1, đoạn 1',
    'data quality over quantity for LLM generalization',
    'data quality over quantity'),
  'survey-cpt-observations': surveyParagraph('S4.I1.i3.p1.1', '§4.1.2, OBS-3',
    'Except for the recent study which conducts CPT over 159 domains, the longest sequence of pre-training stages explored is 8',
    'the longest sequence of pre-training stages explored is 8'),
  'survey-cpt-temporal': surveyParagraph('S4.SS1.SSS3.p7.1', '§4.1.3, temporal shift',
    'retention of old knowledge, acquisition of new knowledge, and update of the outdated knowledge',
    'update of the outdated knowledge'),
  'survey-cpt-other': surveyParagraph('S4.SS1.SSS3.p10.1', '§4.1.3, đoạn 10',
    'CPT as a more efficient learning paradigm compared to the traditional “combine-and-retrain” approach',
    'more efficient learning paradigm'),
  'survey-dap-summary': surveyParagraph('S4.SS2.p2.1', '§4.2, đoạn 2',
    'a summary of the existing 41 studies utilizing DAP for LLMs in Table 2',
    'existing 41 studies utilizing DAP'),
  'survey-dap-one-stage': surveyParagraph('S4.I2.i1.p1.1', '§4.2.1, OBS-1',
    'only one employs two stages of DAP',
    'only one employs two stages of DAP'),
  'survey-dap-forgetting': surveyParagraph('S4.I2.i2.p1.1', '§4.2.1, OBS-2',
    'the remaining sections (all gray, 28/41) either evaluate the potential negative impacts of DAP or proactively employ CL techniques',
    'all gray, 28/41'),
  'survey-dap-techniques': surveyParagraph('S4.I2.i3.p1.1', '§4.2.1, OBS-3',
    'widespread adoption of CL techniques (22/41) for training domain-specific LLMs',
    'CL techniques (22/41)'),
  'survey-lawyer-10b': surveyParagraph('S4.SS2.SSS2.p2.1', '§4.2.2, legal domain',
    'totaling approximately 10 billion tokens as noted in a GitHub issue',
    'approximately 10 billion tokens'),
  'survey-me-llama': surveyParagraph('S4.SS2.SSS2.p4.1', '§4.2.2, medical domain',
    'mixes in about 25% of the general-domain data for DAP',
    'about 25% of the general-domain data'),
  'survey-dap-landscape': surveyParagraph('S4.SS2.SSS2.p1.1', '§4.2.2, đoạn 1',
    'work aimed at establishing vertical LLMs across various domains, including legal, medical, financial, scientific, and code',
    'including legal, medical, financial, scientific, and code'),
  'survey-cft-count-cil': surveyParagraph('S4.I3.i1.p1.1', '§4.3.1, OBS-1',
    'among all 35 papers presented in Table 3, only 3 papers study CFT of CIL',
    'only 3 papers study CFT of CIL'),
  'survey-cft-count-techniques': surveyParagraph('S4.I3.i1.p1.1', '§4.3.1, OBS-2',
    'all 35 papers explicitly deploy the CL techniques, 50% of which develop new techniques',
    'all 35 papers explicitly deploy the CL techniques'),
  'survey-cft-landscape': surveyParagraph('S4.SS3.p1.1', '§4.3, đoạn 1',
    'These topics include Continual Instruction Tuning, Continual Model Refinement, Continual Model Alignment, and Continual Learning for Multimodal Language Models',
    'Continual Instruction Tuning'),
  'survey-cit': surveyParagraph('S4.SS3.SSS3.p2.1', '§4.3.3, đoạn 2',
    'DynaInst merges parameter regularization with dynamic replay',
    'parameter regularization with dynamic replay'),
  'survey-cmr': surveyParagraph('S4.SS3.SSS4.p3.1', '§4.3.4, đoạn 3',
    'the location for storing the fact may not coincide with the best place for editing it',
    'may not coincide with the best place for editing it'),
  'survey-cma': surveyParagraph('S4.SS3.SSS5.p2.1', '§4.3.5, đoạn 2',
    'there are two types of CMA frameworks: RL-based and SL-based',
    'RL-based and SL-based'),
  'survey-multimodal': surveyParagraph('S4.SS3.SSS6.p3.1', '§4.3.6, đoạn 3',
    'a consistent efficacy of replay-based and model expansion strategies across diverse scenarios',
    'replay-based and model expansion strategies'),
  'survey-core-metrics': surveyParagraph('A2.SS1.p3.2', 'Appendix B.1, sau Eq. 12',
    'This enhancement is typically measured by negating the forgetting, thus indicating an improvement in performance on earlier tasks.',
    'measured by negating the forgetting'),
  'survey-eval-lama': surveyParagraph('S5.p1.1', '§5, đoạn 1',
    'LAMA converts each world fact into a cloze statement',
    'each world fact into a cloze statement'),
  'survey-eval-fuar': surveyParagraph('S5.p1.1', '§5, đoạn 1',
    'A FUAR value of 1 represents an equal trade-off between the knowledge forgetting and knowledge learning',
    'equal trade-off between the knowledge forgetting and knowledge learning'),
  'survey-eval-xdelta': surveyParagraph('S5.p1.1', '§5, đoạn 1',
    'quantifying the forward transfer on specific abilities of LLMs',
    'forward transfer on specific abilities of LLMs'),
  'survey-benchmarks': surveyParagraph('S5.p2.1', '§5, đoạn 2',
    'We intentionally exclude datasets used for domain-adaptive pre-training LLMs in vertical domains',
    'intentionally exclude datasets used for domain-adaptive pre-training'),
  'survey-anticipatory': surveyParagraph('S6.SS1.p1.1', '§6.1, đoạn 1',
    'recover forgotten information on documents even before encountering them again',
    'before encountering them again'),
  'survey-new-roles': surveyParagraph('S6.SS2.p2.1', '§6.2, đoạn 2',
    'The importance of DIL is self-evident, given the shared task definition and input-output format',
    'The importance of DIL is self-evident'),
  'survey-memory': surveyParagraph('S6.SS3.p1.1', '§6.3, đoạn 1',
    'the challenge shifts from storage efficiency to computational efficiency',
    'storage efficiency to computational efficiency'),
  'survey-preferences': surveyParagraph('S6.SS4.p4.1', '§6.4, đoạn 4',
    'Early attempts in this direction include Imprecise Bayesian Continual Learning',
    'Imprecise Bayesian Continual Learning'),
  'survey-conclusion': surveyParagraph('S7.p1.1', '§7, đoạn 1',
    'the development of robust and self-evolving AI systems',
    'robust and self-evolving AI systems'),
  'survey-synthesis': surveyParagraph('S1.p4.1', '§1, course framework',
    'three key stages of LLM learning within modern CL',
    'three key stages of LLM learning'),
};

type LessonOccurrenceReview = {
  lessonId: string;
  claimId: string;
  paperIds: readonly string[];
  surveySnippetKeys: readonly string[];
  occurrenceNumbers?: readonly number[];
  evidenceIds?: readonly string[];
};

type LessonOccurrenceReviewOptions = {
  occurrenceNumbers?: readonly number[];
  evidenceIds?: readonly string[];
};

function review(
  lessonId: string,
  claimId: string,
  paperIds: readonly string[],
  surveySnippetKeys: readonly string[] = [],
  options: LessonOccurrenceReviewOptions = {},
): LessonOccurrenceReview {
  if (options.occurrenceNumbers && options.occurrenceNumbers.length !== paperIds.length) {
    throw new Error(`${lessonId} occurrence numbers must match its reviewed paper count.`);
  }
  if (options.evidenceIds && options.evidenceIds.length !== paperIds.length) {
    throw new Error(`${lessonId} evidence IDs must match its reviewed paper count.`);
  }
  return { lessonId, claimId, paperIds, surveySnippetKeys, ...options };
}

// These rows preserve stable occurrence identities. The same paper may occur more
// than once because evidence is reviewed against a local claim occurrence, not only a paper ID.
const lessonOccurrenceReviews: readonly LessonOccurrenceReview[] = [
  review('continual-learning-llm-overview', 'static-model-and-update-motivation', [
    'kaplan2020scaling',
    'hoffmann2022chinchilla',
    'thulke2024climategpt',
    'dou2024sailor',
    'vo2024vimistralx',
    'shi2024continualSurvey',
    'thulke2024climategpt',
    'thulke2024climategpt',
    'thulke2024climategpt',
    'shi2024continualSurvey',
  ], [
    'overview-retrieval-model-editing',
    'overview-cl-goal',
  ], { evidenceIds: [
    'overview-retrain-scaling-kaplan',
    'overview-retrain-scaling-hoffmann',
    'overview-rag-external-context',
    'overview-vietnamese-adaptation-sailor',
    'overview-vietnamese-adaptation-vimistral',
    'overview-retrieval-model-editing',
    'overview-climategpt-cpt',
    'overview-climategpt-ift',
    'overview-climategpt-rag',
    'overview-cl-goal',
  ] }),
  review('continual-learning-llm-overview', 'sequential-learning-interference',
    ['mccloskey1989catastrophic'], [], { evidenceIds: ['overview-catastrophic-interference'] }),
  review('vertical-horizontal-continuity', 'vertical-horizontal-framework', ['qin2023recyclable', 'shi2024continualSurvey'], ['survey-vertical-horizontal']),
  review('cl-methods-taxonomy-and-replay', 'cl-method-taxonomy', ['wang2024comprehensive', 'shi2024unified']),
  review('stability-plasticity-dilemma', 'stability-plasticity-tradeoff', [
    'wang2024comprehensive',
    'gururangan2020dont',
    'jin2022lifelong',
    'chaudhry2019tiny',
    'qi2023fine',
    'shi2024continualSurvey',
  ], [
    'survey-cl-retention',
  ], {
    evidenceIds: [
      'stability-plasticity-tradeoff-01-wang2024comprehensive',
      'stability-plasticity-factor-01-gururangan',
      'stability-plasticity-factor-02-jin',
      'stability-plasticity-factor-03-chaudhry',
      'stability-plasticity-factor-04-qi',
      'stability-plasticity-tradeoff-06-shi2024continualSurvey',
    ],
  }),
  review('catastrophic-forgetting-in-llms', 'catastrophic-forgetting-foundation', ['mccloskey1989catastrophic', 'shi2024continualSurvey'], ['survey-llm-challenges']),
  review('catastrophic-forgetting-code-lab', 'lab-forgetting-interpretation', ['zheng2025spurious']),
  review('cl-settings-til-dil-cil', 'til-dil-cil-settings', ['van2022three', 'kim2022theoretical', 'shi2024continualSurvey'], ['survey-settings']),
  review('replay-introduction', 'replay-generalization-limit', ['shi2024unified', 'shi2024continualSurvey'], ['survey-replay']),
  review('replay-experience-code-lab', 'replay-lab-boundary', ['zheng2025spurious', 'zheng2025spurious']),
  review('parameter-regularization-ewc', 'parameter-regularization', ['kirkpatrick2017overcoming', 'zenke2017continual', 'shi2024continualSurvey'], ['survey-regularization']),
  review('parameter-regularization-ewc', 'function-regularization', ['hinton2015distilling', 'romero2014fitnets', 'li2017learning', 'buzzega2020dark', 'li2017learning'], [], { evidenceIds: [
    'distillation-retention-01-hinton2015distilling',
    'distillation-retention-02-romero2014fitnets',
    'distillation-retention-03-li2017learning',
    'distillation-retention-04-buzzega2020dark',
    'distillation-retention-05-li2017learning',
  ] }),
  review('architecture-expansion-isolation', 'architecture-expansion', ['shi2024continualSurvey', 'wistuba2023', 'wistuba2023', 'shi2024continualSurvey'], ['survey-architecture', 'survey-architecture']),
  review('supplier-consumer-pipeline', 'supplier-consumer', ['qin2023recyclable', 'shi2024continualSurvey', 'qin2023recyclable'], ['survey-supplier-consumer-motivation']),
  review('continuity-to-learning-stages', 'chapter-four-continuity-map', ['shi2024continualSurvey', 'shi2024unified'], ['survey-learning-stages']),
  review('vertical-cl-deep-dive', 'vertical-specialization-pipeline', [
    'shi2024continualSurvey',
    'shi2024continualSurvey',
    'qin2023recyclable',
    'shi2024continualSurvey',
  ], [
    'survey-vertical',
    'survey-learning-stages',
    'survey-vertical',
  ]),
  review('vertical-forgetting', 'vertical-forgetting', [
    'shi2024continualSurvey',
    'shi2024continualSurvey',
    'wistuba2023',
    'shi2024continualSurvey',
    'shi2024continualSurvey',
  ], [
    'survey-vertical',
    'survey-vertical-distribution-coverage',
    'survey-vertical-two-challenges',
    'survey-upstream-data',
  ]),
  review('horizontal-cl-deep-dive', 'horizontal-adaptation', [
    'shi2024continualSurvey',
    'jin2022lifelong',
    'shi2024continualSurvey',
  ], [
    'survey-horizontal',
    'survey-memory',
  ]),
  review('horizontal-forgetting', 'horizontal-forgetting', [
    'shi2024continualSurvey',
    'jin2022lifelong',
    'shi2024continualSurvey',
    'shi2024continualSurvey',
  ], [
    'survey-horizontal',
    'survey-horizontal-two-challenges',
    'survey-horizontal-abrupt',
  ]),
  review('continual-pretraining-pipeline', 'cpt-pipeline', ['shi2024continualSurvey'], ['survey-cpt-pipeline']),
  review('domain-adaptive-pretraining', 'dap-pipeline', ['gururangan2020dont', 'shi2024continualSurvey', 'shi2024continualSurvey'], ['survey-dap-summary', 'survey-dap-summary']),
  review('dap-observations', 'dap-survey-observations', ['shi2024continualSurvey', 'shi2024continualSurvey', 'shi2024continualSurvey'], ['survey-dap-one-stage', 'survey-dap-forgetting', 'survey-dap-techniques']),
  review('dap-domain-landscape', 'dap-domain-landscape', ['shi2024continualSurvey', 'huang2023lawyer', 'colombo2024saullm7b', 'guo2023continuous', 'shi2024continualSurvey', 'xie2024me', 'Chen2023HuatuoGPTII', 'yan2023af', 'Lu2023BBTFin', 'li2023cfgpt', 'takahashi2024pretraining', 'xie2023efficient', 'Zhang2023xuanyuan', 'Bi2023OCEANGPT', 'deng2023learning', 'Nguyen2023AstroLLaMA', 'Zheng2023MarineGPT', 'thulke2024climategpt', 'lin2023geogalactica', 'Azerbayev2023LLEMMA', 'Yang2023PLLaMa', 'rozière2024code', 'paul2024ircoder', 'wu2024llama', 'han2021econet', 'zhou2020pre', 'cheng2024adapting', 'shen2024tag', 'nakamura2024aurora', 'fujii2024continual', 'dou2024sailor', 'shi2024continualSurvey'], ['survey-lawyer-10b', 'survey-me-llama', 'survey-dap-landscape']),
  review('continual-finetuning-overview', 'cft-overview', ['shi2024continualSurvey', 'shi2024continualSurvey', 'zhao2024sapt', 'das2024larimar', 'lin2024mitigating', 'mehta2023empirical', 'zheng2023learn', 'mehta2023empirical', 'winata2023overcoming', 'zheng2023learn', 'ke2021achieve', 'qin2021lfpt5', 'chen2024parameterizing', 'shi2024continualSurvey'], ['survey-cft-count-cil', 'survey-cft-count-techniques', 'survey-cft-landscape']),
  review('continual-instruction-tuning', 'continual-instruction-tuning', ['shi2024continualSurvey', 'scialom2022fine', 'he2024dont', 'huang2024mitigating', 'mok2023large', 'yin2022contintin', 'wang2023orthogonal', 'zhao2024sapt'], ['survey-cit']),
  review('continual-model-refinement', 'continual-model-refinement', ['shi2024continualSurvey', 'hartvigsen2023aging', 'yu2023melo', 'das2024larimar', 'hu2024wilke', 'wang2024wise', 'hase2023does'], ['survey-cmr']),
  review('continual-model-alignment', 'continual-model-alignment', ['shi2024continualSurvey', 'lin2024mitigating', 'zhangcppo', 'zhang2023copf'], ['survey-cma']),
  review('continual-multimodal-llms', 'continual-multimodal-learning', ['shi2024continualSurvey', 'zhai2023investigating', 'zheng2024antiforgetting', 'he2023continual', 'zhu2024model', 'zhao2024reconstruct', 'chen2024coin'], ['survey-multimodal']),
  review('cpt-effectiveness-efficiency', 'cpt-effectiveness-efficiency', ['qin2022elle', 'amba2021dynamic', 'xie2023efficient', 'shi2024continualSurvey'], ['survey-cpt-efficiency']),
  review('cpt-observations', 'cpt-study-observations', ['yildiz2024investigating', 'shi2024continualSurvey'], ['survey-cpt-observations']),
  review('cpt-distribution-shifts', 'cpt-distribution-shifts', ['li2024examining', 'yildiz2024investigating', 'gupta2023continual', 'ibrahim2024simple', 'jin2022lifelong', 'qin2023recyclable', 'gururangan2022demix', 'chen2023lifelong', 'cossu2022continual', 'jang2022towards', 'jang2022temporalwiki', 'jin2022lifelong', 'dhingra2022time', 'shi2024continualSurvey'], ['survey-cpt-temporal']),
  review('cpt-other-directions', 'cpt-other-directions', ['zhao2024large', 'lin2024rho', 'chen2024take', 'amba2021dynamic', 'loureiro2022timelms', 'attanasio2023worth', 'shi2024continualSurvey'], ['survey-cpt-other']),
  review('core-cl-metrics', 'core-cl-metrics', ['shi2024continualSurvey', 'chaudhry2019tiny', 'lopez2017gradient'], ['survey-core-metrics']),
  review('lama-knowledge-evaluation', 'knowledge-and-capability-evaluation', ['petroni2019language', 'jang2022towards', 'jang2022towards', 'petroni2019language', 'shi2024continualSurvey', 'jang2022towards', 'jang2022towards', 'shi2024continualSurvey', 'wang2023trace', 'wang2023trace', 'shi2024continualSurvey'], ['survey-eval-lama', 'survey-eval-fuar', 'survey-eval-xdelta']),
  review('continual-learning-benchmarks', 'continual-benchmark-map', ['shi2024continualSurvey'], ['survey-benchmarks']),
  review('anticipatory-recovering', 'anticipatory-recovery', ['shi2024continualSurvey', 'yang2024reawakening'], ['survey-anticipatory']),
  review('til-dil-cil-new-roles', 'incremental-settings-for-llms', ['shi2024continualSurvey'], ['survey-new-roles']),
  review('memory-bottlenecks', 'memory-access-bottlenecks', ['shi2024continualSurvey'], ['survey-memory']),
  review('continual-llm-research-frontiers', 'research-frontiers', ['wang2024comprehensive', 'shi2024unified', 'he2024dont', 'jin2024model', 'das2024larimar', 'ramsauer2021hopfield', 'lu2023ibcl', 'shi2024continualSurvey'], ['survey-preferences']),
  review('continual-llm-conclusion', 'survey-conclusion', ['shi2024continualSurvey'], ['survey-conclusion']),
  review('continual-llm-synthesis', 'course-synthesis', ['shi2024continualSurvey'], ['survey-synthesis']),
];

export const continualLearningCitationLinkOnlyExceptions = [
  {
    id: 'continual-model-alignment-03-zhangcppo-link-only',
    lessonId: 'continual-model-alignment',
    claimId: 'continual-model-alignment',
    paperId: 'zhangcppo',
    reason: 'The canonical OpenReview target currently returns a browser-verification interstitial, so no exact excerpt can be maintained safely; the link remains explicit and adjacent verified alignment sources cover the broader claim.',
    verificationUrl: 'https://openreview.net/forum?id=86zAUE80pP',
    reviewedAt,
  },
] as const satisfies readonly LearningCitationLinkOnlyException[];

const linkOnlyExceptionOccurrenceIds = new Set(
  continualLearningCitationLinkOnlyExceptions.map((item) => item.id.replace(/-link-only$/, '')),
);

const reviewedOccurrenceSnippetOverrides: Readonly<Record<string, string>> = {
  'overview-catastrophic-interference': 'mccloskey1989catastrophic',
  'vertical-horizontal-framework-01-qin2023recyclable': 'qin2023recyclable-supplier',
  'cl-method-taxonomy-01-wang2024comprehensive': 'wang2024comprehensive-taxonomy',
  'lab-forgetting-interpretation-01-zheng2025spurious': 'zheng2025spurious-biography',
  'architecture-expansion-02-wistuba2023': 'wistuba2023-overview',
  'distillation-retention-05-li2017learning': 'li2017learning-query-limits',
  'vertical-forgetting-03-wistuba2023': 'wistuba2023-frozen-lora',
  'supplier-consumer-01-qin2023recyclable': 'qin2023recyclable-supplier',
  'vertical-specialization-pipeline-03-qin2023recyclable': 'qin2023recyclable-supplier',
  'horizontal-adaptation-03-shi2024continualSurvey': 'survey-memory',
  'dap-domain-landscape-11-takahashi2024pretraining': 'takahashi2024pretraining-rag-evaluation',
  'dap-domain-landscape-02-huang2023lawyer': 'huang2023lawyer-replay',
  'dap-domain-landscape-04-guo2023continuous': 'guo2023continuous-tradeoff',
  'cft-overview-08-mehta2023empirical': 'mehta2023empirical-sam',
  'cft-overview-10-zheng2023learn': 'zheng2023learn-seq',
  'cft-overview-11-ke2021achieve': 'ke2021achieve-modules',
  'cft-overview-05-lin2024mitigating': 'lin2024mitigating-hma',
  'continual-instruction-tuning-06-yin2022contintin': 'yin2022contintin-strategies',
  'continual-model-refinement-02-hartvigsen2023aging': 'hartvigsen2023aging-key-value',
  'continual-model-refinement-03-yu2023melo': 'yu2023melo-vector-database',
  'continual-model-alignment-02-lin2024mitigating': 'lin2024mitigating-hma',
  'continual-multimodal-learning-04-he2023continual': 'he2023continual-expansion',
  'continual-multimodal-learning-05-zhu2024model': 'zhu2024model-patch',
  'continual-multimodal-learning-06-zhao2024reconstruct': 'zhao2024reconstruct-components',
  'continual-multimodal-learning-07-chen2024coin': 'chen2024coin-experts',
  'knowledge-and-capability-evaluation-10-wang2023trace': 'wang2023trace-gsm8k',
  'research-frontiers-01-wang2024comprehensive': 'wang2024comprehensive-taylor',
};

const occurrenceCitationEvidence = lessonOccurrenceReviews.flatMap((lesson) => {
  let surveyIndex = 0;
  const evidence = lesson.paperIds.flatMap((paperId, index): LearningCitationEvidence[] => {
    const occurrenceNumber = lesson.occurrenceNumbers?.[index] ?? index + 1;
    const occurrenceId = lesson.evidenceIds?.[index]
      ?? `${lesson.claimId}-${String(occurrenceNumber).padStart(2, '0')}-${paperId}`;
    const surveySourceKey = paperId === 'shi2024continualSurvey'
      ? lesson.surveySnippetKeys[surveyIndex++]
      : undefined;
    const sourceKey = reviewedOccurrenceSnippetOverrides[occurrenceId]
      ?? (reviewedSourceSnippets[occurrenceId] ? occurrenceId : undefined)
      ?? surveySourceKey
      ?? paperId;
    if (linkOnlyExceptionOccurrenceIds.has(occurrenceId)) return [];
    if (!sourceKey) throw new Error(`${occurrenceId} is missing a reviewed survey snippet mapping.`);
    const snippet = reviewedSourceSnippets[sourceKey];
    if (!snippet) throw new Error(`${occurrenceId} references unknown reviewed source snippet ${sourceKey}.`);
    return [{
      id: occurrenceId,
      lessonId: lesson.lessonId,
      claimId: lesson.claimId,
      paperId,
      ...snippet,
    }];
  });
  if (surveyIndex !== lesson.surveySnippetKeys.length) {
    throw new Error(`${lesson.lessonId} has unused reviewed survey snippet mappings.`);
  }
  return evidence;
});

export const continualLearningCitationEvidence: readonly LearningCitationEvidence[] = occurrenceCitationEvidence;

export const continualLearningCitationEvidenceById: ReadonlyMap<string, LearningCitationEvidence> = new Map(
  continualLearningCitationEvidence.map((item) => [item.id, item]),
);

export const continualLearningCitationLinkOnlyExceptionById: ReadonlyMap<string, LearningCitationLinkOnlyException> = new Map(
  continualLearningCitationLinkOnlyExceptions.map((item) => [item.id, item]),
);

export function getContinualLearningLessonCitationEvidence(lessonId: string): readonly LearningCitationEvidence[] {
  return continualLearningCitationEvidence.filter((item) => item.lessonId === lessonId);
}

export function getContinualLearningLessonCitationLinkOnlyExceptions(lessonId: string): readonly LearningCitationLinkOnlyException[] {
  return continualLearningCitationLinkOnlyExceptions.filter((item) => item.lessonId === lessonId);
}
