import type { LearningCitationEvidence } from '../../../core/learning/citationEvidence.ts';

const climateGptLicenseUrl = 'https://creativecommons.org/licenses/by-sa/4.0/';

export const continualLearningCitationEvidence: readonly LearningCitationEvidence[] = [
  {
    id: 'overview-rag-external-context',
    lessonId: 'continual-learning-llm-overview',
    claimId: 'static-model-and-update-motivation',
    paperId: 'thulke2024climategpt',
    excerpt: 'retrieving relevant documents from external databases and providing these documents as additional context to the model',
    searchText: 'providing these documents as additional context to the model',
    locator: '§4, đoạn 2',
    verificationUrl: 'https://arxiv.org/html/2401.09646v1#S4.p2',
    targetPrecision: 'html-anchor',
    sourceVersion: 'arXiv v1',
    retrievedAt: '2026-08-13',
    review: { status: 'verified', verifiedAt: '2026-08-13' },
    quotation: { basis: 'redistributable-license', licenseUrl: climateGptLicenseUrl },
  },
  {
    id: 'overview-retrieval-model-editing',
    lessonId: 'continual-learning-llm-overview',
    claimId: 'static-model-and-update-motivation',
    paperId: 'shi2024continualSurvey',
    excerpt: 'incorporate editing through retrieval mechanisms',
    searchText: 'incorporate editing through retrieval mechanisms',
    locator: '§4.3.4, đoạn 1',
    verificationUrl: 'https://arxiv.org/html/2404.16789v3#S4.SS3.SSS4.p1',
    targetPrecision: 'html-anchor',
    sourceVersion: 'arXiv v3',
    retrievedAt: '2026-08-13',
    review: { status: 'verified', verifiedAt: '2026-08-13' },
    quotation: { basis: 'short-quotation' },
  },
  {
    id: 'overview-domain-adaptation',
    lessonId: 'continual-learning-llm-overview',
    claimId: 'static-model-and-update-motivation',
    paperId: 'shi2024continualSurvey',
    excerpt: 'facilitate effective adaptation of LLMs to downstream tasks',
    searchText: 'effective adaptation of LLMs to downstream tasks',
    locator: '§4.2, đoạn 1',
    verificationUrl: 'https://arxiv.org/html/2404.16789v3#S4.SS2.p1',
    targetPrecision: 'html-anchor',
    sourceVersion: 'arXiv v3',
    retrievedAt: '2026-08-13',
    review: { status: 'verified', verifiedAt: '2026-08-13' },
    quotation: { basis: 'short-quotation' },
  },
  {
    id: 'overview-climategpt-cpt',
    lessonId: 'continual-learning-llm-overview',
    claimId: 'static-model-and-update-motivation',
    paperId: 'thulke2024climategpt',
    excerpt: 'adapt an existing LLM trained on a large set of general domain data to the target domain',
    searchText: 'adapt an existing LLM',
    locator: '§1.1, Continued Pre-Training',
    verificationUrl: 'https://arxiv.org/html/2401.09646v1#S1.SS1.p4',
    targetPrecision: 'html-anchor',
    sourceVersion: 'arXiv v1',
    retrievedAt: '2026-08-13',
    review: { status: 'verified', verifiedAt: '2026-08-13' },
    quotation: { basis: 'redistributable-license', licenseUrl: climateGptLicenseUrl },
  },
  {
    id: 'overview-climategpt-ift',
    lessonId: 'continual-learning-llm-overview',
    claimId: 'static-model-and-update-motivation',
    paperId: 'thulke2024climategpt',
    excerpt: 'inject instruction-following capabilities into the model',
    searchText: 'inject instruction-following capabilities into the model',
    locator: '§1.1, Instruction Fine-Tuning',
    verificationUrl: 'https://arxiv.org/html/2401.09646v1#S1.SS1.p5',
    targetPrecision: 'html-anchor',
    sourceVersion: 'arXiv v1',
    retrievedAt: '2026-08-13',
    review: { status: 'verified', verifiedAt: '2026-08-13' },
    quotation: { basis: 'redistributable-license', licenseUrl: climateGptLicenseUrl },
  },
  {
    id: 'overview-climategpt-rag',
    lessonId: 'continual-learning-llm-overview',
    claimId: 'static-model-and-update-motivation',
    paperId: 'thulke2024climategpt',
    excerpt: 'implemented with high-quality climate resources to increase factuality as well as to extend the system with new knowledge',
    searchText: 'implemented with high-quality climate resources',
    locator: '§1.1, Retrieval Augmented Generation',
    verificationUrl: 'https://arxiv.org/html/2401.09646v1#S1.SS1.p6',
    targetPrecision: 'html-anchor',
    sourceVersion: 'arXiv v1',
    retrievedAt: '2026-08-13',
    review: { status: 'verified', verifiedAt: '2026-08-13' },
    quotation: { basis: 'redistributable-license', licenseUrl: climateGptLicenseUrl },
  },
  {
    id: 'overview-catastrophic-interference',
    lessonId: 'continual-learning-llm-overview',
    claimId: 'sequential-learning-interference',
    paperId: 'mccloskey1989catastrophic',
    excerpt: 'New learning may interfere catastrophically with old learning when networks are trained sequentially.',
    searchText: 'interfere catastrophically with old learning',
    locator: 'Publisher summary',
    verificationUrl: 'https://www.sciencedirect.com/science/article/abs/pii/S0079742108605368',
    targetPrecision: 'landing-page',
    retrievedAt: '2026-08-13',
    review: { status: 'verified', verifiedAt: '2026-08-13' },
    quotation: { basis: 'short-quotation' },
    automatedAudit: {
      status: 'manual-required',
      reason: 'ScienceDirect returns HTTP 403 to the maintenance fetch; verify the publisher summary in a browser.',
    },
  },
  {
    id: 'overview-cl-goal',
    lessonId: 'continual-learning-llm-overview',
    claimId: 'static-model-and-update-motivation',
    paperId: 'shi2024continualSurvey',
    excerpt: 'maintaining performance across all tasks',
    searchText: 'maintaining performance across all tasks',
    locator: '§1, đoạn 2',
    verificationUrl: 'https://arxiv.org/html/2404.16789v3#S1.p2',
    targetPrecision: 'html-anchor',
    sourceVersion: 'arXiv v3',
    retrievedAt: '2026-08-13',
    review: { status: 'verified', verifiedAt: '2026-08-13' },
    quotation: { basis: 'short-quotation' },
  },
];

export const continualLearningCitationEvidenceById: ReadonlyMap<string, LearningCitationEvidence> = new Map(
  continualLearningCitationEvidence.map((evidence) => [evidence.id, evidence]),
);

export function getContinualLearningLessonCitationEvidence(lessonId: string): LearningCitationEvidence[] {
  return continualLearningCitationEvidence.filter((evidence) => evidence.lessonId === lessonId);
}
