import { readFileSync, writeFileSync } from 'node:fs';
import { learningCatalog } from '../src/content/learning/index.ts';

const STATS_PATH = 'wiki/reference/catalog-stats.md';
const PROSE_PATH = 'wiki/concepts/learning-lab.md';

interface DomainStat {
  id: string;
  status: string;
  tracks: number;
  lessons: number;
  published: number;
}

interface CatalogStats {
  domains: DomainStat[];
  domainCount: number;
  trackCount: number;
  lessonCount: number;
  publishedCount: number;
  placeholderCount: number;
}

function computeCatalogStats(): CatalogStats {
  const domains: DomainStat[] = learningCatalog.domains.map((domain) => {
    const lessons = learningCatalog.lessons.filter((lesson) => lesson.domainId === domain.id);
    const tracks = learningCatalog.tracks.filter((track) => track.domainId === domain.id);
    return {
      id: domain.id,
      status: domain.status,
      tracks: tracks.length,
      lessons: lessons.length,
      published: lessons.filter((lesson) => lesson.contentStatus === 'published').length,
    };
  });
  const publishedCount = domains.reduce((sum, domain) => sum + domain.published, 0);
  return {
    domains,
    domainCount: domains.length,
    trackCount: learningCatalog.tracks.length,
    lessonCount: learningCatalog.lessons.length,
    publishedCount,
    placeholderCount: learningCatalog.lessons.length - publishedCount,
  };
}

function renderStatsMarkdown(stats: CatalogStats): string {
  const rows = stats.domains
    .map((domain) => `| \`${domain.id}\` | ${domain.status} | ${domain.tracks} | ${domain.lessons} | ${domain.published} |`)
    .join('\n');
  return [
    '<!-- AUTO-GENERATED by scripts/generateCatalogStats.ts — do not edit by hand.',
    '     Regenerate with: npm run sync:catalog-stats -->',
    '',
    '# Learning Lab catalog stats',
    '',
    'Single source of truth: the typed domain TOCs under `src/content/learning/`.',
    '',
    '| Domain | Catalog status | Tracks | Lessons | Published MDX |',
    '|---|---|---|---|---|',
    rows,
    '',
    `**Totals:** ${stats.domainCount} domains · ${stats.trackCount} tracks · ${stats.lessonCount} lesson nodes · ${stats.publishedCount} published · ${stats.placeholderCount} placeholders.`,
    '',
  ].join('\n');
}

const SMALL_NUMBERS: Record<string, number> = {
  zero: 0, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9,
  ten: 10, eleven: 11, twelve: 12, thirteen: 13, fourteen: 14, fifteen: 15, sixteen: 16,
  seventeen: 17, eighteen: 18, nineteen: 19, twenty: 20, thirty: 30, forty: 40, fifty: 50,
  sixty: 60, seventy: 70, eighty: 80, ninety: 90,
};

function parseSpelledNumber(phrase: string): number | null {
  let total = 0;
  let current = 0;
  for (const word of phrase.toLowerCase().split(/[\s-]+/)) {
    if (word === 'and') continue;
    if (word === 'hundred') {
      total += (current === 0 ? 1 : current) * 100;
      current = 0;
      continue;
    }
    const value = SMALL_NUMBERS[word];
    if (value === undefined) return null;
    current += value;
  }
  return total + current;
}

interface ProseCheck {
  ok: boolean;
  problems: string[];
}

function checkProseNumbers(stats: CatalogStats, prose: string): ProseCheck {
  const problems: string[] = [];
  const totals = prose.match(/The catalog contains (\d+) domains, (\d+) tracks, and (\d+) lesson nodes\./);
  if (!totals) {
    problems.push('headline sentence "The catalog contains N domains, N tracks, and N lesson nodes." not found');
  } else if (
    Number(totals[1]) !== stats.domainCount
    || Number(totals[2]) !== stats.trackCount
    || Number(totals[3]) !== stats.lessonCount
  ) {
    problems.push(
      `headline counts say ${totals[1]} domains / ${totals[2]} tracks / ${totals[3]} lessons,`
      + ` catalog has ${stats.domainCount} / ${stats.trackCount} / ${stats.lessonCount}`,
    );
  }
  const authored = prose.match(/([A-Za-z][A-Za-z\s-]*?)\s+Vietnamese-first lessons have authored content/);
  if (!authored) {
    problems.push('sentence "… Vietnamese-first lessons have authored content" not found');
  } else {
    const spelled = parseSpelledNumber(authored[1]);
    if (spelled === null) {
      problems.push(`cannot parse authored-lesson count "${authored[1].trim()}"`);
    } else if (spelled !== stats.publishedCount) {
      problems.push(
        `prose says ${spelled} authored lessons, catalog has ${stats.publishedCount} published`,
      );
    }
  }
  const placeholders = prose.match(/The other (\d+) nodes are navigable placeholders/);
  if (!placeholders) {
    problems.push('sentence "The other N nodes are navigable placeholders" not found');
  } else if (Number(placeholders[1]) !== stats.placeholderCount) {
    problems.push(
      `prose says ${placeholders[1]} placeholder nodes, catalog has ${stats.placeholderCount}`,
    );
  }
  return { ok: problems.length === 0, problems };
}

const checkMode = process.argv.includes('--check');
const stats = computeCatalogStats();
const rendered = renderStatsMarkdown(stats);

if (checkMode) {
  let failed = false;
  try {
    const onDisk = readFileSync(STATS_PATH, 'utf8');
    if (onDisk !== rendered) {
      console.warn(`⚠️ ${STATS_PATH} is stale. Regenerate with: npm run sync:catalog-stats`);
      failed = true;
    }
  } catch {
    console.warn(`⚠️ ${STATS_PATH} missing. Generate with: npm run sync:catalog-stats`);
    failed = true;
  }
  const prose = readFileSync(PROSE_PATH, 'utf8');
  const proseCheck = checkProseNumbers(stats, prose);
  if (!proseCheck.ok) {
    console.warn(`⚠️ ${PROSE_PATH} headline numbers drifted from the catalog:`);
    for (const problem of proseCheck.problems) console.warn(`  - ${problem}`);
    console.warn('Update the prose (or TOCs) — the typed catalog is the source of truth.');
    failed = true;
  }
  if (failed) process.exit(1);
  console.log('✨ Catalog stats file and prose headline numbers match the catalog.');
} else {
  writeFileSync(STATS_PATH, rendered);
  console.log(`✅ Wrote ${STATS_PATH}: ${stats.domainCount} domains · ${stats.trackCount} tracks · ${stats.lessonCount} lessons · ${stats.publishedCount} published.`);
}
