import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

const SURVEY_ARXIV_ID = '2510.25117v2';
const SURVEY_SOURCE_URL = `https://export.arxiv.org/e-print/${SURVEY_ARXIV_ID}`;
const TAUGHT_SURVEY_SECTION_ROOTS = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6'];
const CANONICAL_IDENTITY_OVERRIDES = {
  biderman2023pythia: { arxivId: '2304.01373', url: 'https://arxiv.org/abs/2304.01373' },
  meng2022locating: { arxivId: '2202.05262', url: 'https://arxiv.org/abs/2202.05262' },
};
const outputPath = path.resolve('src/content/learning/llm-unlearning/papers.generated.ts');
const previousRecords = readPreviousRecords(outputPath);
const temporaryRoot = mkdtempSync(path.join(tmpdir(), 'torchviz-llm-unlearning-references-'));

try {
  const archivePath = path.join(temporaryRoot, 'survey.tar');
  const htmlPath = path.join(temporaryRoot, 'survey.html');
  execFileSync('curl', ['-L', '--fail', '--silent', '--show-error', SURVEY_SOURCE_URL, '-o', archivePath]);
  execFileSync('curl', ['-L', '--fail', '--silent', '--show-error', `https://arxiv.org/html/${SURVEY_ARXIV_ID}`, '-o', htmlPath]);
  execFileSync('tar', ['-xf', archivePath, '-C', temporaryRoot]);
  const bibliography = readFileSync(path.join(temporaryRoot, 'ref.bib'), 'utf8');
  const latex = [
    'sec/1_intro.tex',
    'sec/2_definition.tex',
    'sec/3_methods.tex',
    'sec/4_evaluation.tex',
    'sec/5_challenges.tex',
    'sec/6_conclusions.tex',
  ].map((filePath) => readFileSync(path.join(temporaryRoot, filePath), 'utf8')).join('\n');
  const html = readFileSync(htmlPath, 'utf8');
  const externalLinksByPaperId = collectBibliographyLinks(html);
  const entries = parseBibtex(bibliography);
  const directReferencesBySection = collectSectionReferences(latex);
  const referencesBySection = includeDescendantReferences(directReferencesBySection);
  const citedIds = new Set(TAUGHT_SURVEY_SECTION_ROOTS.flatMap((sectionId) => referencesBySection[sectionId] ?? []));
  const missingIds = [...citedIds].filter((id) => !entries.has(id)).sort();
  missingIds.forEach((id) => citedIds.delete(id));
  if (missingIds.length) {
    process.stderr.write(`Skipping survey citation keys absent from ref.bib: ${missingIds.join(', ')}\n`);
  }
  const taughtDirectReferences = filterSectionReferences(directReferencesBySection, citedIds);
  const taughtReferences = filterSectionReferences(referencesBySection, citedIds);

  const records = await mapWithConcurrency([...citedIds].sort(), 2, async (id) => {
    let record = toPaperRecord(id, entries.get(id), externalLinksByPaperId.get(id) ?? []);
    const previous = previousRecords.get(id);
    if (record.url.includes('scholar.google.com') && previous && !previous.url.includes('scholar.google.com')) {
      record = compact({ ...record, year: record.year ?? previous.year, doi: previous.doi, arxivId: previous.arxivId, url: previous.url });
    }
    return record.url.includes('scholar.google.com') ? resolveCanonicalIdentity(record) : record;
  });
  const source = `// Generated by scripts/generateLlmUnlearningReferences.mjs from arXiv:${SURVEY_ARXIV_ID}.\n`
    + `// Do not hand-edit bibliographic records or survey section coverage.\n\n`
    + `export type LlmUnlearningPaperKind = 'article' | 'book' | 'incollection' | 'inproceedings' | 'misc' | 'phdthesis' | 'techreport' | 'unknown';\n\n`
    + `export type LlmUnlearningPaper = {\n`
    + `  id: string;\n  title: string;\n  authors: string[];\n  year: number | null;\n`
    + `  venue?: string;\n  doi?: string;\n  arxivId?: string;\n  url: string;\n  kind: LlmUnlearningPaperKind;\n};\n\n`
    + `export const llmUnlearningPapers = ${JSON.stringify(records, null, 2)} as const satisfies readonly LlmUnlearningPaper[];\n\n`
    + `export const surveyDirectReferenceIdsBySection = ${JSON.stringify(sortObject(taughtDirectReferences), null, 2)} as const;\n\n`
    + `export const surveyReferenceIdsBySection = ${JSON.stringify(sortObject(taughtReferences), null, 2)} as const;\n`;
  writeFileSync(outputPath, source);
  process.stdout.write(`Generated ${records.length} LLM-unlearning papers across ${Object.keys(taughtReferences).length} survey sections at ${outputPath}\n`);
} finally {
  rmSync(temporaryRoot, { recursive: true, force: true });
}

function parseBibtex(source) {
  const entries = new Map();
  const entryPattern = /^@(article|book|incollection|inproceedings|misc|phdthesis)\s*\{\s*([^,\r\n]+),/gim;
  for (const match of source.matchAll(entryPattern)) {
    const start = match.index + match[0].length;
    let depth = 1;
    let index = start;
    for (; index < source.length && depth > 0; index += 1) {
      if (source[index] === '{') depth += 1;
      else if (source[index] === '}') depth -= 1;
    }
    const body = source.slice(start, index - 1);
    const supportedKinds = new Set(['article', 'book', 'incollection', 'inproceedings', 'misc', 'phdthesis', 'techreport']);
    const normalizedKind = match[1].toLowerCase();
    entries.set(match[2].trim(), { kind: supportedKinds.has(normalizedKind) ? normalizedKind : 'unknown', fields: parseFields(body) });
  }
  return entries;
}

function parseFields(body) {
  const fields = {};
  let index = 0;
  while (index < body.length) {
    const fieldMatch = body.slice(index).match(/(?:^|,)\s*([A-Za-z][A-Za-z0-9_-]*)\s*=\s*/);
    if (!fieldMatch) break;
    index += fieldMatch.index + fieldMatch[0].length;
    const key = fieldMatch[1].toLowerCase();
    const opener = body[index];
    if (opener === '{' || opener === '"') {
      const closer = opener === '{' ? '}' : '"';
      let depth = opener === '{' ? 1 : 0;
      const valueStart = index + 1;
      index += 1;
      for (; index < body.length; index += 1) {
        if (opener === '{' && body[index] === '{') depth += 1;
        if (body[index] !== closer) continue;
        if (opener === '"' || --depth === 0) break;
      }
      fields[key] = body.slice(valueStart, index).trim();
      index += 1;
    } else {
      const end = body.indexOf(',', index);
      fields[key] = body.slice(index, end < 0 ? body.length : end).trim();
      index = end < 0 ? body.length : end;
    }
  }
  return fields;
}

function collectSectionReferences(source) {
  const sectionRefs = {};
  const counters = [0, 0, 0];
  const stack = [];
  const lines = source.split(/\r?\n/).filter((line) => !line.trimStart().startsWith('%'));
  for (const line of lines) {
    const heading = line.match(/^\\(section|subsection|subsubsection)\*?\{/);
    if (heading) {
      const level = { section: 0, subsection: 1, subsubsection: 2 }[heading[1]];
      counters[level] += 1;
      for (let index = level + 1; index < counters.length; index += 1) counters[index] = 0;
      stack.length = level;
      stack[level] = `S${counters.slice(0, level + 1).join('.SS').replace('S1.SS', 'S1.SS')}`;
      const sectionId = level === 0
        ? `S${counters[0]}`
        : level === 1
          ? `S${counters[0]}.SS${counters[1]}`
          : `S${counters[0]}.SS${counters[1]}.SSS${counters[2]}`;
      stack[level] = sectionId;
      sectionRefs[sectionId] ??= new Set();
    }
    const ids = [...line.matchAll(/\\cite\w*\s*(?:\[[^\]]*\]\s*)?\{([^}]+)\}/g)]
      .flatMap((match) => match[1].split(',').map((id) => id.trim()).filter(Boolean));
    if (!ids.length) continue;
    const sectionId = stack.at(-1);
    if (!sectionId) continue;
    sectionRefs[sectionId] ??= new Set();
    ids.forEach((id) => {
      sectionRefs[sectionId].add(id);
    });
  }
  return Object.fromEntries(Object.entries(sectionRefs).map(([id, values]) => [id, [...values].sort()]));
}

function includeDescendantReferences(directReferences) {
  return Object.fromEntries(Object.keys(directReferences).map((sectionId) => {
    const prefix = `${sectionId}.`;
    const ids = Object.entries(directReferences)
      .filter(([candidate]) => candidate === sectionId || candidate.startsWith(prefix))
      .flatMap(([, values]) => values);
    return [sectionId, [...new Set(ids)].sort()];
  }));
}

function filterSectionReferences(references, citedIds) {
  return Object.fromEntries(Object.entries(references)
    .filter(([sectionId]) => TAUGHT_SURVEY_SECTION_ROOTS.some((root) => sectionId === root || sectionId.startsWith(`${root}.`)))
    .map(([sectionId, paperIds]) => [sectionId, paperIds.filter((paperId) => citedIds.has(paperId))]));
}

function toPaperRecord(id, entry, externalLinks) {
  const fields = entry.fields;
  const doi = clean(fields.doi).replace(/^https?:\/\/(?:dx\.)?doi\.org\//i, '');
  const explicitUrl = clean(fields.url);
  const externalArxivUrl = externalLinks.find((url) => /arxiv\.org\/(?:abs|pdf)\//i.test(url));
  const externalDoiUrl = externalLinks.find((url) => /doi\.org\//i.test(url));
  const arxivId = extractArxivId(fields, [explicitUrl, externalArxivUrl].filter(Boolean).join(' '));
  const venue = clean(fields.journal ?? fields.booktitle ?? fields.publisher ?? fields.institution ?? fields.school);
  const yearValue = Number(clean(fields.year));
  return compact({
    id,
    title: clean(fields.title) || id,
    authors: splitAuthors(fields.author),
    year: Number.isInteger(yearValue) ? yearValue : null,
    venue,
    doi,
    arxivId,
    url: doi ? `https://doi.org/${doi}` : explicitUrl || externalDoiUrl || (arxivId ? `https://arxiv.org/abs/${arxivId}` : externalLinks[0]) || `https://scholar.google.com/scholar?q=${encodeURIComponent(clean(fields.title) || id)}`,
    kind: entry.kind,
    ...(CANONICAL_IDENTITY_OVERRIDES[id] ?? {}),
  });
}

async function resolveCanonicalIdentity(record) {
  try {
    const endpoint = new URL('https://api.openalex.org/works');
    endpoint.searchParams.set('search', record.title);
    endpoint.searchParams.set('per-page', '5');
    const response = await fetchWithRetry(endpoint, 3);
    if (!response.ok) return record;
    const payload = await response.json();
    const normalizedTitle = normalizeTitle(record.title);
    const match = payload.results?.find((candidate) => {
      if (normalizeTitle(candidate.title ?? '') !== normalizedTitle) return false;
      return !record.year || !candidate.publication_year || Math.abs(candidate.publication_year - record.year) <= 1;
    });
    if (!match) return record;
    const doi = String(match.doi ?? '').replace(/^https?:\/\/(?:dx\.)?doi\.org\//i, '');
    const locations = [match.primary_location, ...(match.locations ?? [])].filter(Boolean);
    const arxivUrl = locations.map((location) => location.landing_page_url).find((url) => /arxiv\.org\/abs\//i.test(url ?? ''));
    const arxivId = arxivUrl?.match(/arxiv\.org\/abs\/([^?#/]+)/i)?.[1];
    const primaryUrl = locations.map((location) => location.landing_page_url).find((url) => /^https?:\/\//i.test(url ?? ''));
    return compact({
      ...record,
      year: record.year ?? match.publication_year ?? null,
      doi,
      arxivId,
      url: doi ? `https://doi.org/${doi}` : arxivUrl || primaryUrl || record.url,
    });
  } catch {
    return record;
  }
}

async function fetchWithRetry(url, attempts) {
  for (let attempt = 0; attempt < attempts; attempt += 1) {
    const response = await fetch(url, { headers: { 'User-Agent': 'TorchViz-3D citation generator' } });
    if (response.status !== 429 || attempt === attempts - 1) return response;
    await new Promise((resolve) => setTimeout(resolve, 750 * (attempt + 1)));
  }
  throw new Error('unreachable');
}

function readPreviousRecords(filePath) {
  if (!existsSync(filePath)) return new Map();
  try {
    const source = readFileSync(filePath, 'utf8');
    const serialized = source.match(/export const llmUnlearningPapers = (\[[\s\S]*?\]) as const satisfies/)?.[1];
    const records = serialized ? JSON.parse(serialized) : [];
    return new Map(records.map((record) => [record.id, record]));
  } catch {
    return new Map();
  }
}

async function mapWithConcurrency(values, concurrency, mapper) {
  const results = new Array(values.length);
  let nextIndex = 0;
  async function worker() {
    while (nextIndex < values.length) {
      const index = nextIndex;
      nextIndex += 1;
      results[index] = await mapper(values[index], index);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, values.length) }, worker));
  return results;
}

function normalizeTitle(value) {
  return value.normalize('NFKD').replace(/[^a-z0-9]+/gi, ' ').trim().toLowerCase();
}

function collectBibliographyLinks(html) {
  const bibliographyIdByPaperId = new Map();
  for (const match of html.matchAll(/<a href="#(bib\.bib\d+)"[^>]*>([^<]+)<\/a>/g)) {
    bibliographyIdByPaperId.set(decodeHtml(match[2]).trim(), match[1]);
  }
  const linksByBibliographyId = new Map();
  for (const match of html.matchAll(/<li id="(bib\.bib\d+)"[\s\S]*?<\/li>/g)) {
    const links = [...match[0].matchAll(/href="(https?:[^"#]+)"/g)].map((item) => decodeHtml(item[1]));
    linksByBibliographyId.set(match[1], [...new Set(links)]);
  }
  return new Map([...bibliographyIdByPaperId].map(([paperId, bibliographyId]) => [paperId, linksByBibliographyId.get(bibliographyId) ?? []]));
}

function decodeHtml(value) {
  return value.replaceAll('&amp;', '&').replaceAll('&#x2F;', '/').replaceAll('&#47;', '/');
}

function extractArxivId(fields, url) {
  const candidates = [fields.eprint, fields.arxiv, fields.journal, fields.doi, url].filter(Boolean).join(' ');
  return candidates.match(/(?:arXiv[.:/]\s*|arxiv\.org\/(?:abs|pdf)\/|abs\/)(\d{4}\.\d{4,5}(?:v\d+)?)/i)?.[1];
}

function splitAuthors(value = '') {
  return value.split(/\s+and\s+/i).map(clean).filter(Boolean);
}

function clean(value = '') {
  return value
    .replace(/[{}]/g, '')
    .replace(/\\&/g, '&')
    .replace(/\\text(?:tt|it|bf)\s*/g, '')
    .replace(/\\["'`^~=.]\s*([A-Za-z])/g, '$1')
    .replace(/\\[A-Za-z]+\s*/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function compact(value) {
  return Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined && item !== ''));
}

function sortObject(value) {
  return Object.fromEntries(Object.entries(value).sort(([left], [right]) => left.localeCompare(right)));
}
